examples/with-ethers/README.md, examples/with-ethers/src/index.ts, examples/with-ethers/src/weth-contract-abi.json, tsconfig.base.json
ABI taken from https://goerli.etherscan.io/address/0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6
```
$ pnpm run start
Network:
goerli (chain ID 5)
Address:
0xA16d17B5bd27b657dB0E973983B8C1848aeC257e
Balance:
0.023383035198168014 Ether
Transaction count:
14
Turnkey-signed transaction:
0x02f8668080808080942ad9ea1e677949a536a270cec812d6e868c881088609184e72a00080c001a0cae70a2ffd4b851ea22349c8f198a3aa8e47932064eecdc1691fa8ed65d09281a015434a47976515b60783cdc1c3f52fa29ff0e36575c31cf59f41b9802d95a8f5
Sent 0.00001 Ether to 0x2Ad9eA1E677949a536A270CEC812D6e868C88108:
https://goerli.etherscan.io/tx/0x9ced217b3eb54d2d0dd49e62602af1584039091571c95489a63f0cd76601f81c
WETH Balance:
0.00023 WETH
Deposited 0.00001 WETH:
https://goerli.etherscan.io/tx/0xec76157de7c02ddf5a188273f238f1d194040ad1034e9037d9f30b10f …
```
=> [easy] Example: call WETH contract

packages/ethers/src/index.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts
`a768b259bcd4c1fd2f0c54fffbad172d94a40a38`
`keyId` -> `privateKeyId`
CI
=> Sync latest proto from mono

examples/with-ethers/src/createNewEthereumPrivateKey.ts, packages/ethers/src/index.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts
`bcee86a5c2ae3f1e355eb0f13ab074f4385b1bea`
typecheck
=> Sync latest proto from internal

examples/sweeper/README.md, examples/sweeper/package.json, examples/sweeper/src/provider.ts, examples/sweeper/src/scripts/index.ts, examples/sweeper/src/utils.ts, examples/sweeper/tsconfig.json, pnpm-lock.yaml
Simple script to sweep ones funds to a new address.
=> Add sweeper utility

README.md, examples/with-ethers/README.md, examples/with-ethers/src/index.ts, packages/ethers/src/__tests__/index-test.ts, packages/ethers/src/index.ts
Add an example for signing raw message payloads via Turnkey.
Next up: EIP712 payloads!
=> sign raw messages

.gitignore, examples/sweeper/.env.local.example, examples/with-uniswap/.env.local.example
=> add example envs templates

.gitignore, README.md, examples/deployer/.env.local.example, examples/deployer/README.md, examples/deployer/package.json, examples/deployer/src/compile.ts, examples/deployer/src/contracts/HelloWorld.sol, examples/deployer/src/createNewEthereumPrivateKey.ts, examples/deployer/src/index.ts, examples/deployer/tsconfig.json, pnpm-lock.yaml
$title
This PR is scoped to using `solc` specifically. Some future integrations to think about: Hardhat, Foundry, etc.
https://paulojeronimo.com/ethereum-helloworld-tutorial/
https://docs.soliditylang.org/en/v0.8.19/using-the-compiler.html
https://github.com/ethereum/solc-js
=> add a deployment example using solc

packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts
=> update proto-related gen files

packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts
Pulls in update files with corrections + x-readme (extension) info.
=> [easy] update gen

packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json
=> bump sdk version to 0.10.0

examples/with-uniswap/src/base.ts, examples/with-uniswap/src/scripts/main.ts
=> import correct file for uniswap example

examples/with-gnosis/README.md, examples/with-gnosis/src/index.ts, examples/with-uniswap/README.md
$title
Also minor readme updates.
=> recommend using sepolia + infura for the gnosis example

packages/http/src/__tests__/request-test.ts, packages/http/src/base.ts
Quick way to include grpc status details in the error message.
Unit
=> Includes grpc error details in error message

packages/ethers/src/__tests__/index-test.ts
=> Fixes the mono e2e tests

packages/ethers/src/__tests__/index-test.ts
- updated in this PR: https://github.com/tkhq/mono/pull/1614
e2e
=> update policy engine deny error

examples/with-solana/.env.local.example, examples/with-solana/README.md, examples/with-solana/package.json, examples/with-solana/src/createSolanaKey.ts, examples/with-solana/src/createSolanaTransfer.ts, examples/with-solana/src/faucet.ts, examples/with-solana/src/index.ts, examples/with-solana/src/solanaAddress.ts, examples/with-solana/src/solanaNetwork.ts, examples/with-solana/tsconfig.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, pnpm-lock.yaml
This example showcases Solana key creation and transaction signing
Ran this example against our production API. Link to onchain Solana tx: https://explorer.solana.com/tx/5rKMD3a97LZxwEVj4ZRvsC5h2pGL36Wz5Tj6o2YkDB8XkhvMapmRoXf7G56QPtHF9LtzHEKcJ24m4seZkbmxUics?cluster=devnet
=> New example: `with-solana`

README.md
Realized I forgot to add this example to the list!
=> Add `with-solana` to the list of examples in the main README

examples/with-ethers/README.md, examples/with-ethers/package.json, examples/with-ethers/src/legacySepolia.ts
=> add legacy transaction example

examples/with-federated-passkeys/CHANGELOG.md, examples/with-federated-passkeys/package.json, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json
Fairly routine version bumps, but most notably includes federated requests via https://github.com/tkhq/sdk/pull/82
=> version bumps with changelogs

examples/with-cosmjs/package.json, package.json, packages/cosmjs/package.json, packages/ethers/README.md, pnpm-lock.yaml
Noticed this tiny inconsistency while updating docs
This should be followed up with a release at some point -- not particularly urgent.
=> Update `ethers` readme examples, cosmjs deps

.changeset/late-pumas-buy.md, examples/deployer/src/createNewEthereumPrivateKey.ts, examples/with-cosmjs/src/createNewCosmosPrivateKey.ts, examples/with-ethers/src/createNewEthereumPrivateKey.ts, examples/with-federated-passkeys/CHANGELOG.md, examples/with-federated-passkeys/package.json, examples/with-federated-passkeys/src/pages/index.tsx, examples/with-gnosis/src/createNewEthereumPrivateKey.ts, examples/with-nonce-manager/src/createNewEthereumPrivateKey.ts, examples/with-offline/src/index.ts, examples/with-solana/src/createSolanaKey.ts, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/http/src/__tests__/async-test.ts
Updates the types for the http package.
=> Update types for http package

examples/with-gnosis/README.md, examples/with-gnosis/src/index.ts
=> cleanup gnosis example

.changeset/chilled-years-smile.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts
=> release 08-02

packages/viem/CHANGELOG.md
Ran changeset generation with `pnpm changeset`
=> Add @turnkey/viem CHANGELOG file

packages/viem/README.md
Of all things...the title was off! Also fixed some links: relative links do not work once published on NPM.
=> Fix @turnkey/viem README

packages/viem/CHANGELOG.md, packages/viem/package.json
=> Release @turnkey/viem v0.1.1

packages/http/README.md
=> minor docs clarification

packages/viem/CHANGELOG.md, packages/viem/README.md, packages/viem/package.json
Followup to #99: I forgot to fix the code sample in the Viem README. Patch release!
=> README fixes for `@turnkey/viem`

examples/with-ethers/README.md, examples/with-ethers/package.json, examples/with-ethers/src/createNewEthereumPrivateKey.ts, examples/with-federated-passkeys/.env.local.example, examples/with-federated-passkeys/README.md, examples/with-federated-passkeys/package.json, examples/with-federated-passkeys/src/pages/api/proxyRequest.ts, examples/with-federated-passkeys/src/pages/api/subOrg.ts, examples/with-federated-passkeys/src/pages/index.tsx, examples/with-offline/.env.local.example, examples/with-offline/README.md, examples/with-offline/package.json, examples/with-offline/src/index.ts, examples/with-solana/package.json, examples/with-solana/src/createSolanaKey.ts, examples/with-solana/src/createSolanaTransfer.ts, examples/with-solana/src/index.ts, examples/with-solana/src/solanaAddress.ts, examples/with-uniswap/.env.local.example, examples/with-uniswap/README.md, examples/with-uniswap/src/provider.ts, examples/with-viem-and-passkeys/src/pages/api/createKey.ts, examples/with-viem-and-passkeys/src/pages/api/subOrg.ts, pnpm-lock.yaml
The hard part is manually testing that these run correctly! All of the examples I touched work:
* with-ethers
* with-federated-passkeys
* with-offline
* with-solana
* with-uniswap (didn't need meaningful upgrade)
* with-viem (didn't need meaningful upgrade)
* with-viem-and-passkeys (didn't need meaningful upgrade)
I've also taken a look at READMEs and fixed a few things here and there.
=> Migrate half of the examples to use new `TurnkeyClient`

examples/with-viem-and-passkeys/src/pages/index.tsx
This was flagged by `pnpm build` in that folder.
=> Escape quote in `with-viem-and-passkeys` example

examples/with-federated-passkeys/src/pages/api/subOrg.ts, examples/with-viem-and-passkeys/src/pages/api/subOrg.ts, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Bump http package version

packages/ethers/CHANGELOG.md, packages/ethers/package.json
To release https://github.com/tkhq/sdk/pull/113
=> bump ethers for stamper support

packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/viem/CHANGELOG.md, packages/viem/package.json, packages/webauthn-stamper/CHANGELOG.md, packages/webauthn-stamper/package.json, packages/webauthn-stamper/src/universal.ts
Primary changes:
- Sync protos from mono
- Introduce new activities
- Minor/bug fixes:
- Require base URL upon initialization of `@turnkey/http`
- Polyfill `Buffer`
=> release v2023.10.1

packages/http/src/webauthn.ts
https://github.com/tkhq/sdk/issues/123
Examples
=> add conditional check

.changeset/seven-bulldogs-mix.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/viem/CHANGELOG.md, packages/viem/package.json
Updating the generated file with our latest release
=> Update @turnkey/http with latest release

packages/http/CHANGELOG.md
$title; realized we didn't make explicit mention of our new version of suborgs.
=> update changelog to include sub org v4

.changeset/good-kangaroos-punch.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/http/src/webauthn.ts
🏠 🧹 
`npm run typecheck-all`
`npm run build-all`
=> update api spec, simplify types

.changeset/thirty-buses-suffer.md, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> release signWith

packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts
=> simplify types again

packages/http/CHANGELOG.md, packages/viem/src/__tests__/index-test.ts
=> remove cruft

package.json, packages/api-key-stamper/package.json, packages/api-key-stamper/tsconfig.esm.json, packages/cosmjs/package.json, packages/cosmjs/tsconfig.esm.json, packages/ethers/package.json, packages/ethers/tsconfig.esm.json, packages/http/package.json, packages/http/tsconfig.esm.json, packages/iframe-stamper/package.json, packages/iframe-stamper/tsconfig.esm.json, packages/viem/package.json, packages/viem/tsconfig.esm.json, packages/webauthn-stamper/package.json, packages/webauthn-stamper/tsconfig.esm.json
Cloning #154 to make sure CI runs properly, with secrets injected. If CI passes here, I'll merge #154 and close this PR.
=> (clone) chore: add esm to package dist

.changeset/good-kangaroos-punch.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
Small release, which includes:
* new ESM artifacts in package dist (#154)
* further type simplification for enums (#152)
=> Release packages (2023-11-03)

packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/iframe-stamper/CHANGELOG.md, packages/iframe-stamper/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Changes for release v2023.11.4

.changeset/breezy-kangaroos-pay.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json, packages/webauthn-stamper/CHANGELOG.md, packages/webauthn-stamper/package.json
Only one change in this release: #179
=> Release packages (2023-11-28)

.changeset/afraid-flowers-behave.md, .changeset/late-rivers-play.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/version.ts, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Update for release v2024.1.1

.changeset/thin-mayflies-destroy.md, packages/viem/CHANGELOG.md, packages/viem/package.json
=> update viem package

.changeset/hungry-otters-destroy.md, packages/solana/CHANGELOG.md, packages/solana/package.json
=> Release `@turnkey/solana` 0.2.0

examples/with-solana/README.md, examples/with-solana/package.json, examples/with-solana/src/createSolanaTransfer.ts, examples/with-solana/src/index.ts, examples/with-solana/src/signMessage.ts, examples/with-solana/src/solanaNetwork.ts, examples/with-solana/src/util.ts, pnpm-lock.yaml
$title; smol followup for https://github.com/tkhq/sdk/pull/202
ran locally …
=> add signing to example; update deprecated methods

packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json
=> release v2024.1.2

.changeset/fifty-dingos-mate.md, packages/solana/CHANGELOG.md, packages/solana/package.json
Patch release to include #218 and release `@turnkey/solana` v0.3.1
=> Release `@turnkey/solana` v0.3.1

.changeset/hip-bears-wash.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Update api types and cut release

packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
Bump generated files to latest, and release packages.
=> Release v2024.3.14

.changeset/spotty-rabbits-grab.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Sync protos with release 2024.3.16

packages/sdk-js-server/package.json, packages/sdk-react/LICENSE, packages/sdk-react/README.md, packages/sdk-react/jest.config.js, packages/sdk-react/package.json, packages/sdk-react/rollup.config.mjs, packages/sdk-react/src/contexts/TurnkeyContext.tsx, packages/sdk-react/src/hooks/useTurnkey.ts, packages/sdk-react/src/index.ts, packages/sdk-react/tsconfig.json, packages/sdk-react/tsconfig.typecheck.json, pnpm-lock.yaml
Isolates the React SDK into it's own package
=> creates react sdk for react context + hooks

examples/rebalancer/package.json, examples/rebalancer/src/index.ts, examples/rebalancer/src/provider.ts, examples/rebalancer/src/requests/createActivityApproval.ts, examples/rebalancer/src/requests/createActivityRejection.ts, examples/rebalancer/src/requests/createPolicy.ts, examples/rebalancer/src/requests/createPrivateKey.ts, examples/rebalancer/src/requests/createPrivateKeyTag.ts, examples/rebalancer/src/requests/createUser.ts, examples/rebalancer/src/requests/createUserTag.ts, examples/rebalancer/src/requests/getActivities.ts, examples/rebalancer/src/requests/getActivity.ts, examples/rebalancer/src/requests/getPrivateKeysForTag.ts, examples/rebalancer/src/send.ts, packages/sdk-browser/scripts/codegen.js, packages/sdk-browser/src/__generated__/sdk-client-base.ts, packages/sdk-browser/src/__types__/base.ts, packages/sdk-server/scripts/codegen.js, packages/sdk-server/src/__generated__/sdk-client-base.ts, packages/sdk-server/src/__types__/base.ts, pnpm-lock.yaml
$title
- bugfixes for the rebalancer example
- use sdk-js-server where possible (with the exception being for the `TurnkeySigner` creation; that will have to wait for https://github.com/tkhq/sdk/pull/239)
- adjust codegen for the following case regarding activity approval/rejection
before
```
activity result: {
signTransactionResult: {
signedTransaction: '02f87483aa36a780847735940084774fcd2082520894741e6bbe594c2229f849ed12ca3df4d8dd9855ba8706f82991b7563880c001a0b83a639a7bddd3831ee0c15b986dcdb2271baac7e3f5ddc8c421bad83d88ec30a017bb80169aa3d54158276f3293e534e6de315ee32d8efb81d2271033037dd0aa'
},
activity: {
id: '3c90c015-20f1-4f8e-96ed-7069bd558065',
status: 'ACTIVITY_STATUS_COMPLETED'
}
}
```
after
```
activity result: {
signTransactionResult: {
signedTransaction: …
```
=> use server sdk for rebalancer

packages/sdk-browser/CHANGELOG.md, packages/sdk-react/CHANGELOG.md, packages/sdk-server/CHANGELOG.md
=> add changelogs

packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts
=> drop alpha

examples/with-solana/package.json, packages/solana/package.json, pnpm-lock.yaml
=> resolve high severity deps

.changeset/silent-rocks-cry.md, .gitignore, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> bump ethers viem

packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> bump sdk packages

packages/sdk-browser/src/__generated__/version.ts, packages/sdk-server/src/__generated__/version.ts
=> bump versions

.changeset/unlucky-hotels-hammer.md, examples/rebalancer/src/requests/createActivityApproval.ts, examples/rebalancer/src/requests/createActivityRejection.ts, examples/rebalancer/src/requests/createPolicy.ts, examples/rebalancer/src/requests/createPrivateKey.ts, examples/rebalancer/src/requests/createPrivateKeyTag.ts, examples/rebalancer/src/requests/createUser.ts, examples/rebalancer/src/requests/createUserTag.ts, examples/rebalancer/src/requests/getActivities.ts, examples/rebalancer/src/requests/getActivity.ts, examples/rebalancer/src/requests/getPrivateKeysForTag.ts, examples/with-ethers/src/index.ts, examples/with-federated-passkeys/src/pages/api/createSubOrg.ts, examples/with-federated-passkeys/src/pages/api/getActivity.ts, examples/with-federated-passkeys/src/pages/api/getWallet.ts, examples/with-viem/src/index.ts, packages/sdk-server/src/__tests__/request-test.ts, packages/sdk-server/src/sdk-client.ts
=> sdk client consistency

README.md, examples/email-auth/README.md, examples/email-recovery/README.md, packages/http/CHANGELOG.md
We moved some pages around, causing 404s for some existing links in this repo. Noticed by @demisx in #273 🎖️ 
This PR fixes this!
=> Update doc links

.changeset/chilled-shirts-lay.md, .changeset/five-terms-march.md, .changeset/shaggy-chicken-act.md, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/iframe-stamper/CHANGELOG.md, packages/iframe-stamper/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> bump iframe stamper

packages/sdk-browser/src/sdk-client.ts
=> update login response type

.changeset/giant-ants-taste.md, packages/crypto/CHANGELOG.md, packages/crypto/package.json
=> crypto patch fix

packages/sdk-browser/src/sdk-client.ts
=> add `extractKeyEncryptedBundle` method

packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts
=> release v2024.5.9

.changeset/tasty-teachers-wonder.md, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> passkey sessions release

.changeset/pink-roses-wait.md, packages/viem/src/index.ts
Would like to utilize the existing viem account functions but want to create our own custom viem account abstraction object
N/A
yes 
These changes will be used at release time to determine what packages to …
=> chore: export viem account functions

packages/crypto/CHANGELOG.md, packages/crypto/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
Release commit for @turnkey/crypto v0.2.0
=> Jordan moe/bump crypto version

packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Major release for sdk browser, server, react native (Oauth Integration)

examples/with-viem/src/legacy/index.ts
=> update viem legacy script

examples/email-auth/src/pages/api/auth.ts, examples/email-auth/src/pages/index.tsx, examples/with-federated-passkeys/src/pages/api/createSubOrg.ts, examples/with-federated-passkeys/src/pages/index.tsx
$title -- adding suborg support to these flows
- local …
=> updated examples for suborgs

packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Email Auth V2

examples/email-auth/package.json, examples/email-recovery/package.json, examples/wallet-import-export/package.json, examples/with-federated-passkeys/package.json, pnpm-lock.yaml
closes https://github.com/tkhq/sdk/issues/326 …
=> resolve axios cve

examples/with-solana/README.md, examples/with-solana/src/advanced.ts, examples/with-solana/src/faucet.ts, examples/with-solana/src/index.ts, examples/with-solana/src/tokenTransfer.ts, examples/with-solana/src/utils/createSolanaTransfer.ts, examples/with-solana/src/utils/index.ts, examples/with-solana/src/utils/solanaNetwork.ts
=> solana versioned transaction example

examples/deployer/README.md, examples/email-auth/README.md, examples/email-recovery/README.md, examples/rebalancer/README.md, examples/sweeper/README.md, examples/trading-runner/README.md, examples/wallet-import-export/README.md, examples/with-cosmjs/README.md, examples/with-eip-1193-provider/README.md, examples/with-ethers/README.md, examples/with-federated-passkeys/README.md, examples/with-gnosis/README.md, examples/with-nonce-manager/README.md, examples/with-offline/README.md, examples/with-solana/README.md, examples/with-uniswap/README.md, examples/with-viem/README.md, examples/with-wallet-stamper/README.md
=> recommend node v18+

.changeset/pink-pets-build.md, examples/with-wallet-stamper/CHANGELOG.md, examples/with-wallet-stamper/package.json, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Release V2024.8.15 - Changelog

.changeset/nervous-bananas-know.md, examples/with-solana/package.json, examples/with-solana/src/advanced.ts, examples/with-solana/src/index.ts, examples/with-solana/src/tokenTransfer.ts, examples/with-solana/src/utils/createSolanaWallet.ts, examples/with-wallet-stamper/CHANGELOG.md, examples/with-wallet-stamper/package.json, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/solana/src/__tests__/index-test.ts, packages/solana/src/index.ts, pnpm-lock.yaml
$title
unit, examples
yessir 🫡  …
=> update solana to allow multiple client types

examples/wallet-import-export/src/components/Export.tsx
=> Update export example to include apply settings to export iframe

.changeset/stupid-windows-love.md, examples/with-wallet-stamper/CHANGELOG.md, examples/with-wallet-stamper/package.json, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Release Aug 29

README.md, examples/with-solana/package.json, examples/with-solana/src/jupiterSwap.ts, examples/with-solana/src/utils/index.ts, examples/with-solana/src/utils/retrySender.ts, pnpm-lock.yaml
Example successful tx: https://solscan.io/tx/4tkFaZQPGNYTBag6sNTawpBnAodqiBNF494y86s2qBLohQucW1AHRaq9Mm3vWTSxFRaUTmtdYp67pbBRz5RDoAdr
Unsigned payload: 
```
0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800100070ae05271368f77a2c5fefe77ce50e2b2f93ceb671eee8b172734c8d4df9d9eddc186a35856664b03306690c1c0fbd4b5821aea1c64ffb8c368a0422e47ae0d2895de288ba87b903021e6c8c2abf12c2484e98b040792b1fbb87091bc8e0dd76b6600000000000000000000000000000000000000000000000000000000000000000306466fe5211732ffecadba72c39be7bc8ce5bbc5f7126b2c439b3a400000000479d55bf231c06eee74c56ece681507fdb1b2dea3f48e5102b1cda256bc138f06ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a98c97258f4e2489f1bb3d1029148e0d830b5a1399daff1084048e7bd …
```
=> add jupiter swap example

examples/with-gnosis/package.json, pnpm-lock.yaml
$title. No need for the offending dependency at all :) 
```
Run pnpm audit --audit-level high
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ body-parser vulnerable to denial of service when url   │
│                     │ encoding is enabled                                    │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ body-parser                                            │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ <1.20.3                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=1.20.3 …
```
=> bump body parser

.changeset/fuzzy-terms-juggle.md, .changeset/popular-rats-dance.md, .changeset/twenty-flies-own.md, examples/with-wallet-stamper/CHANGELOG.md, examples/with-wallet-stamper/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Release sep 11

.changeset/hip-turtles-cheat.md, examples/with-wallet-stamper/CHANGELOG.md, examples/with-wallet-stamper/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
This release includes a single PR: #364
=> Release - 2024.09.12

.changeset/calm-oranges-build.md, .changeset/rare-seas-flash.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-browser/src/models.ts, packages/sdk-browser/src/sdk-client.ts, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts
Implements login + read/write sessions.
Also adds documentation/does a lil cleanup
Add an example similar to Email Auth
These changes will be used at release time to determine what packages to publish and how …
=> read+write session

.changeset/wild-chefs-grab.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/sdk-browser/src/__generated__/sdk-client-base.ts, packages/sdk-browser/src/__generated__/sdk_api_types.ts, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-server/src/__generated__/sdk-client-base.ts, packages/sdk-server/src/__generated__/sdk_api_types.ts, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts
=> release v2024.9.31

.changeset/spotty-buses-check.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/sdk-browser/src/sdk-client.ts, packages/sdk-server/src/sdk-client.ts, packages/viem/src/index.ts
=> fix for type issues viem

.changeset/spotty-buses-check.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/sdk-browser/src/sdk-client.ts, packages/sdk-server/src/sdk-client.ts, packages/viem/src/index.ts
This reverts commit 0265dc991e32527dbd080bd8a45842b642bb2fa9, reversing changes made to 780eedea4bac59332191a3e50f3733ca99b67263.
These changes will be used at release time to determine what packages to …
=> Revert "Merge pull-request #391"

.changeset/clean-emus-tickle.md, packages/crypto/package.json, packages/crypto/src/__tests__/crypto-test.ts, packages/crypto/src/crypto.ts, packages/crypto/src/index.ts, packages/crypto/src/turnkey.ts, packages/encoding/src/index.ts, pnpm-lock.yaml
$title
See changelog / in-line code comments for more details
- unit
- 🫡  …
=> add verify stamp method

examples/with-solana/package.json, examples/with-solana/src/addSignature.ts
=> add example using addSignature

packages/solana/src/index.ts
=> Add org id override to addSignature

packages/http/CHANGELOG.md
=> minor changelog update

examples/with-biconomy-aa/CHANGELOG.md, examples/with-biconomy-aa/README.md, examples/with-biconomy-aa/package.json, examples/with-biconomy-aa/src/ethers.ts, examples/with-biconomy-aa/src/nexus-viem.ts, examples/with-biconomy-aa/src/viem.ts, examples/with-eth-passkeys-galore/src/pages/index.tsx, pnpm-lock.yaml
$title
See updated README + CHANGELOG
- Local …
=> add biconomy nexus support

.changeset/curly-eyes-cover.md, examples/kitchen-sink/package.json, examples/with-eth-passkeys-galore/package.json, examples/with-solana-passkeys/package.json, examples/with-wallet-stamper/package.json, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/crypto/CHANGELOG.md, packages/crypto/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json, packages/wallet-stamper/CHANGELOG.md, packages/wallet-stamper/package.json
=> @turnkey/crypto minor release + associated dependants: add KeyFormat to export

.changeset/shiny-coats-scream.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/sdk-browser/src/__generated__/sdk-client-base.ts, packages/sdk-browser/src/__generated__/sdk_api_types.ts, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-server/src/__generated__/sdk-client-base.ts, packages/sdk-server/src/__generated__/sdk_api_types.ts, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts
=> Update api endpoints

.changeset/moody-files-sort.md
=> Changeset: update solana packages with newest version of web3.js

.changeset/wet-tools-deliver.md, examples/react-components/src/app/dashboard/page.tsx, packages/sdk-react/src/actions/initOtpAuth.ts, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/OtpVerification.tsx
Add a user identifier to components and example for enforcing sms rate limits …
=> Sms rate limiiting

.changeset/three-clocks-switch.md, packages/sdk-react/README.md
=> Add README to sdk-react

.changeset/three-clocks-switch.md, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json
=> Update sdk react to add readme

.changeset/cyan-beers-promise.md, packages/sdk-browser/src/turnkey-helpers.ts, packages/sdk-server/src/turnkey-helpers.ts
=> Add xrp default format

examples/wallet-import-export/src/pages/api/exportWallet.ts, examples/wallet-import-export/src/pages/api/getWallets.ts, examples/wallet-import-export/src/pages/api/importWallet.ts, examples/wallet-import-export/src/pages/api/initImportWallet.ts, examples/wallet-import-export/src/pages/api/whoami.ts
=> feat: use NEXT_PUBLIC_BASE_URL env variable for apiBaseUrl if present

examples/with-solana/src/addSignature.ts, examples/with-solana/src/advanced.ts, examples/with-solana/src/index.ts, examples/with-solana/src/utils/createMint.ts, examples/with-solana/src/utils/createSolanaTransfer.ts, examples/with-solana/src/utils/createToken.ts, examples/with-solana/src/utils/createTokenAccount.ts, examples/with-solana/src/utils/createTokenTransfer.ts, examples/with-solana/src/utils/solanaNetwork.ts, examples/with-solana/src/withFeePayer.ts
$title. Makes it easier for someone to use these scripts with mainnet
Locally invoked scripts
These changes will be used at release time to determine what packages to publish and how to bump their version. …
=> allow network configuration in with-solana

packages/eip-1193-provider/README.md, packages/viem/README.md
=> docs: update READMEs with anvil setup instructions

.changeset/breezy-knives-learn.md, .changeset/loud-bulldogs-hide.md, .changeset/lucky-ads-trade.md, .changeset/orange-carrots-sparkle.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
$title
Per mono release v2025.1.11, and other updated packages. …
=> [release] update packages

.changeset/large-masks-peel.md, package.json, packages/sdk-react/rollup.config.mjs, pnpm-lock.yaml
=> Fix bundling issue w/ sdk-react

.changeset/angry-badgers-retire.md, .changeset/breezy-fireants-crash.md, .changeset/good-kangaroos-sneeze.md, .changeset/large-masks-peel.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/crypto/CHANGELOG.md, packages/crypto/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json, packages/wallet-stamper/CHANGELOG.md, packages/wallet-stamper/package.json
=> Release for Feb 11 -  patches, add more country codes to EWK

.changeset/khaki-glasses-teach.md, packages/sdk-react/README.md, packages/sdk-react/package.json, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/OtpVerification.tsx, packages/sdk-react/src/hooks/use-session.ts, packages/sdk-react/src/hooks/use-turnkey.ts, pnpm-lock.yaml
=> Patch fix ewk session length & useLocalStorage errors during compling

.changeset/proud-moles-lie.md, packages/sdk-react/src/components/auth/Auth.tsx
=> EWK: Patch unnecessary suborg creation

README.md
=> Added flutter and react native demos to readme

README.md
=> Fix readme video

.changeset/early-grapes-teach.md, package.json, packages/sdk-browser/package.json, packages/sdk-server/package.json, pnpm-lock.yaml
=> Upgrade elliptic

.changeset/chatty-swans-behave.md, packages/sdk-react/src/components/auth/Auth.tsx, pnpm-lock.yaml
=> Fix phone validation EWK

packages/sdk-browser/package.json, packages/sdk-server/package.json, pnpm-lock.yaml
Unused dependency as far as I can tell? Let's see what the build says.
=> Remove elliptic

.changeset/eight-owls-promise.md, packages/sdk-react/src/components/auth/Apple.tsx
Fixes an issue where mobile login on browser was not consistently working. …
=> Fix apple oidc on mobile web browser

.changeset/modern-cooks-approve.md, packages/sdk-react/src/components/auth/Auth.tsx
=> OTP Sign up patch (sdk-react)

.changeset/shy-chairs-beam.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts
=> Update api per mono release v2025.3.0

.changeset/shy-chairs-beam.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react-native/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Release as per mono v2025.3.0

.changeset/tender-ways-fly.md, .codesandbox/ci.json, examples/react-components/package.json, examples/react-components/src/app/layout.tsx, examples/react-components/src/app/page.tsx, examples/with-sdk-server/tsconfig.json, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/constants.ts, packages/sdk-server/package.json, packages/sdk-server/src/actions.ts, pnpm-lock.yaml
Adds wallet as an authentication option in the Embedded Wallet Kit components for `@turnkey/sdk-react`
These changes will be used at release time to determine what packages to publish and how to bump their …
=> Add wallet auth to ewk and react-components demo

.changeset/old-ghosts-obey.md, .changeset/tender-ways-fly.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
**User Authentication Helpers (`@turnkey/sdk-browser`)**
- Adds `updateUserAuth`, `addUserAuth`, and `deleteUserAuth` helper functions
**Wallet Authentication Support (`@turnkey/sdk-react`)**
- Adds wallet as an authentication option in the Embedded Wallet Kit components
Changes were testing using the demo-ewk with the latest codesandbox built modules
✅
=> Release 2025.03.10

examples/react-components/src/app/dashboard/page.tsx, packages/sdk-browser/scripts/codegen.js, packages/sdk-browser/src/__clients__/browser-clients.ts, packages/sdk-browser/src/__generated__/sdk-client-base.ts, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/OtpVerification.tsx, packages/sdk-server/src/actions.ts
New sessions refactor needed a few more changes in the EWK, sdk-browser and sdk-server. OAuth login, wallet login, update user via otp were not working correctly in demo EWK
No changeset. SDK hasn't been released and its just fixes before release.
=> Updated sdk-react, browser and server to match new sessions changes

.changeset/loud-wombats-protect.md, packages/sdk-react/src/components/auth/Apple.tsx, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/Facebook.tsx, packages/sdk-react/src/components/auth/Google.tsx, packages/sdk-react/src/components/auth/OtpVerification.tsx, packages/sdk-server/src/actions.ts
=> Loading, error exposing on ewk. Exposed email customization

packages/sdk-browser/src/__clients__/browser-clients.ts, packages/sdk-browser/src/index.ts, packages/sdk-browser/src/sdk-client.ts, packages/sdk-react/src/hooks/use-session.ts
=> feat: update session hydration

.changeset/great-apricots-explode.md, packages/sdk-react-native/src/contexts/TurnkeyContext.tsx, packages/sdk-react-native/src/turnkey-helpers.ts
this caused issues when signing with viem …
=> fix imports for TurnkeyClient

.changeset/healthy-berries-work.md, packages/sdk-browser/src/__clients__/browser-clients.ts
$title
Tested via `email-auth` example
Yes …
=> expose getEmbeddedPublicKey() via TurnkeyIframeClient

packages/http/CHANGELOG.md, packages/iframe-stamper/CHANGELOG.md, packages/sdk-browser/CHANGELOG.md, packages/sdk-react/CHANGELOG.md
$title
Adding some [clarity](https://www.youtube.com/watch?v=IxxstCcJlsc) …
=> edit changelogs

packages/api-key-stamper/package.json, packages/cosmjs/package.json, packages/crypto/package.json, packages/eip-1193-provider/package.json, packages/encoding/package.json, packages/ethers/package.json, packages/http/package.json, packages/iframe-stamper/package.json, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/package.json, packages/sdk-react-native/package.json, packages/sdk-react/package.json, packages/sdk-server/package.json, packages/solana/package.json, packages/telegram-cloud-storage-stamper/package.json, packages/viem/package.json, packages/wallet-stamper/package.json, packages/webauthn-stamper/package.json
$title
got sick of waiting for recursive/workspace scripts during releases (publish)
These changes will be used at release time to determine what packages to publish and how to bump their version. For more …
=> edit prepublish hook

.changeset/wild-numbers-kiss.md, packages/sdk-server/src/__types__/base.ts, packages/sdk-server/src/actions.ts
=> Update server action send otp to allow for sendFromEmailSenderName

.changeset/wild-numbers-kiss.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Release patch for server actions

.changeset/fifty-plants-grin.md, examples/with-zerodev-aa/package.json, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/index.ts, packages/eip-1193-provider/src/types.ts, packages/eip-1193-provider/src/utils.ts, pnpm-lock.yaml
=> resolve eip 1193 type

packages/viem/src/__tests__/index-test.ts
=> break up viem tests

.changeset/cold-gorillas-cross.md, .changeset/loud-beds-taste.md, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react-native/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json
sdk-react, sdk-react-native patches …
=> Release apr17

generated-docs/sdks/readme.mdx
Attribution goes to: @mdqst #82 https://github.com/tkhq/sdk/pull/604 …
=> docs: fix typo (thank you @mdqst)

.changeset/hot-actors-wave.md, packages/sdk-react-native/README.md, packages/sdk-react-native/package.json, packages/sdk-react-native/src/contexts/TurnkeyContext.tsx, packages/sdk-react-native/src/index.ts, pnpm-lock.yaml
=> add createSessionFromEmbeddedKey

examples/kitchen-sink/README.md, examples/kitchen-sink/src/http/createApiKey.ts, examples/kitchen-sink/src/http/createEthereumPrivateKey.ts, examples/kitchen-sink/src/http/createEthereumWallet.ts, examples/kitchen-sink/src/http/createPolicy.ts, examples/kitchen-sink/src/http/createPrivateKeyTag.ts, examples/kitchen-sink/src/http/createSolanaPrivateKey.ts, examples/kitchen-sink/src/http/createSolanaWallet.ts, examples/kitchen-sink/src/http/createUser.ts, examples/kitchen-sink/src/http/createUserTag.ts, examples/kitchen-sink/src/http/deleteWallets.ts, examples/kitchen-sink/src/http/setOrganizationFeature.ts, examples/kitchen-sink/src/http/signRawPayload.ts, examples/kitchen-sink/src/http/signTransaction.ts, examples/kitchen-sink/src/http/updateRootQuorum.ts, examples/kitchen-sink/src/http/with-poller/createApiKey.ts, examples/kitchen-sink/src/http/with-poller/createEthereumPrivateKey.ts, examples/kitchen-sink/src/http/with-poller/createEthereumWallet.ts, examples/kitchen-sink/src/http/with-poller/createPolicy.ts, examples/kitchen-sink/src/http/with-poller/createPrivateKeyTag.ts, examples/kitchen-sink/src/http/with-poller/createSolanaPrivateKey.ts, examples/kitchen-sink/src/http/with-poller/createSolanaWallet.ts, examples/kitchen-sink/src/http/with-poller/createUser.ts, examples/kitchen-sink/src/http/with-poller/createUserTag.ts, examples/kitchen-sink/src/http/with-poller/deleteWallets.ts, examples/kitchen-sink/src/http/with-poller/setOrganizationFeature.ts, examples/kitchen-sink/src/http/with-poller/signRawPayload.ts, examples/kitchen-sink/src/http/with-poller/signTransaction.ts, examples/kitchen-sink/src/http/with-poller/updateRootQuorum.ts, examples/kitchen-sink/src/sdk-server/deleteWallet.ts
=> revamp kitchen-sink and add delete wallet

.changeset/olive-dolphins-destroy.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts
=> mono release v2025.4.5

examples/wallet-import-export/src/components/ExportWalletAccount.tsx, examples/wallet-import-export/src/components/WalletsTable.tsx, examples/wallet-import-export/src/pages/api/exportWalletAccount.ts, examples/wallet-import-export/src/pages/api/getWalletAccounts.ts, examples/wallet-import-export/src/pages/wallet/[id].tsx
$title
adds the ability to export wallet accounts within the example
locally
https://github.com/user-attachments/assets/530407f1-4fb9-4c83-859c-cb24f6eb6b04
These changes will be used at release time to …
=> add wallet accounts table + export flow

examples/with-tron/.env.local.example, examples/with-tron/README.md, examples/with-tron/package.json, examples/with-tron/src/createTronWallet.ts, examples/with-tron/src/requests/createPolicy.ts, examples/with-tron/src/requests/createUser.ts, examples/with-tron/src/signRawPayload.ts, examples/with-tron/src/transferTRC20Policy.ts, examples/with-tron/src/transferTRXPolicy.ts, examples/with-tron/tsconfig.json, pnpm-lock.yaml
This example walks through the following:
- Creation of a new Turnkey wallet with a new Tron account
- Obtaining Nile testnet TRX and USDT from a faucet to use for the rest of the examples
- Signing a TRX transaction
- Create a Turnkey policy to parse and guard Tron TRX and TRC-20 transactions
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the command) along with the …
=> with-tron example 

.changeset/fluffy-terms-raise.md, examples/with-zerodev-aa/package.json, examples/with-zerodev-aa/src/eip7702.ts, packages/viem/src/index.ts, pnpm-lock.yaml
=> update zerodev implementation

.changeset/fluffy-terms-raise.md, examples/with-viem/package.json, examples/with-viem/src/eip7702/signRawTransaction.ts, examples/with-viem/src/eip7702/signTransaction.ts, packages/viem/CHANGELOG.md, packages/viem/package.json, pnpm-lock.yaml
=> release viem

.github/workflows/release.yml
=> chore: manually create release

.changeset/kind-hats-sleep.md, .github/workflows/release.yml, packages/sdk-types/CHANGELOG.md, packages/sdk-types/package.json
- merge release PR for `release/test-v0.0.5` …
=> Release/test v0.0.5

.changeset/witty-rabbits-relax.md, packages/sdk-react-native/src/contexts/TurnkeyContext.tsx
=> React native onSessionEmpty

.changeset/real-windows-burn.md, packages/sdk-react/src/components/auth/Apple.tsx, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/Facebook.tsx, packages/sdk-react/src/components/auth/Google.tsx, packages/sdk-react/src/components/auth/constants.ts
=> Patch fix google oauth auth component

.changeset/real-windows-burn.md, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json
=> patch release for google oauth fix in auth component

.changeset/breezy-spoons-type.md, examples/react-components/src/app/page.tsx, packages/sdk-react/src/components/auth/Apple.tsx, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/Facebook.tsx, packages/sdk-react/src/components/auth/Google.tsx, packages/sdk-react/src/components/auth/OtpVerification.tsx
=> Patch fix oauth inpage

examples/oauth/src/pages/api/auth.ts, examples/oauth/src/pages/api/createSuborg.ts, examples/oauth/src/pages/index.tsx
=> updating the oauth example with indexedDbClient

examples/oauth/README.md, examples/oauth/src/pages/index.module.css, examples/oauth/src/pages/index.tsx, examples/otp-auth/README.md, examples/otp-auth/src/pages/api/auth.ts, examples/otp-auth/src/pages/api/init_auth.ts, examples/otp-auth/src/pages/index.module.css, examples/otp-auth/src/pages/index.tsx
=> otp example with indexedDbClient

.github/workflows/version.yml
- use `git add -A` to include ALL files including deleted files (changesets) …
=> chore: debug git status and commit ALL files

.changeset/fluffy-doors-film.md, .changeset/lucky-spiders-hammer.md, examples/delegated-access/CHANGELOG.md, examples/delegated-access/package.json, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react-native/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> chore: release packages

examples/with-sdk-js/src/app/page.tsx, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/sdk-browser/src/__generated__/sdk-client-base.ts, packages/sdk-browser/src/__generated__/sdk_api_types.ts, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-js/scripts/codegen.js, packages/sdk-js/src/__clients__/core.ts, packages/sdk-js/src/__generated__/sdk-client-base.ts, packages/sdk-js/src/__types__/base.ts, packages/sdk-server/src/__generated__/sdk-client-base.ts, packages/sdk-server/src/__generated__/sdk_api_types.ts, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts, packages/sdk-types/scripts/codegen.js, packages/sdk-types/src/__generated__/types.ts, packages/sdk-types/src/__inputs__/public_api.swagger.json, packages/sdk-types/src/__inputs__/public_api.types.ts
=> SDK-Types type generation update

examples/kitchen-sink/src/http/createSubOrganization.ts, examples/kitchen-sink/src/http/with-poller/createSubOrganization.ts, examples/kitchen-sink/src/sdk-server/createSubOrganization.ts
=> add createsuborg example

.changeset/plenty-cheetahs-swim.md, packages/crypto/src/__tests__/crypto-test.ts, packages/crypto/src/crypto.ts
=> update der signature parsing

examples/with-sdk-js/package.json, packages/react-wallet-kit/package.json, packages/react-wallet-kit/src/components/auth/Action.tsx, packages/react-wallet-kit/src/components/auth/Email.tsx, packages/react-wallet-kit/src/components/auth/OAuth.tsx, packages/react-wallet-kit/src/components/auth/OTP.tsx, packages/react-wallet-kit/src/components/auth/OrSeparator.tsx, packages/react-wallet-kit/src/components/auth/Passkey.tsx, packages/react-wallet-kit/src/components/auth/Phone.tsx, packages/react-wallet-kit/src/components/auth/index.tsx, packages/react-wallet-kit/src/components/design/Buttons.tsx, packages/react-wallet-kit/src/components/design/Inputs.tsx, packages/react-wallet-kit/src/index.css, packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/react-wallet-kit/src/providers/modal/Root.tsx, packages/sdk-js/src/__clients__/core.ts, pnpm-lock.yaml
=> React Wallet Kit Branchoff

examples/with-sdk-js/src/app/layout.tsx, packages/react-wallet-kit/src/components/auth/index.tsx, packages/react-wallet-kit/src/providers/TurnkeyProvider.tsx, packages/react-wallet-kit/src/providers/client/Provider.tsx
=> Auth component ordering

examples/with-sdk-js/package.json, examples/with-sdk-js/src/app/layout.tsx, examples/with-sdk-js/src/app/page.tsx, packages/react-wallet-kit/package.json, packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/sdk-js/scripts/codegen.js, packages/sdk-js/src/__clients__/core.ts, packages/sdk-js/src/__generated__/sdk-client-base.ts, packages/sdk-js/src/__stampers__/wallet/base.ts, packages/sdk-js/src/__types__/base.ts, packages/wallet-stamper/package.json, packages/wallet-stamper/src/ethereum.ts, packages/wallet-stamper/src/index.ts, packages/wallet-stamper/src/solana.ts, packages/wallet-stamper/src/stamper.ts, packages/wallet-stamper/src/types.ts, packages/wallet-stamper/src/utils.ts, pnpm-lock.yaml
=> wallet stamper refactor

examples/with-sdk-js/src/app/page.tsx, packages/react-wallet-kit/src/components/sign/Message.tsx, packages/react-wallet-kit/src/components/user/RemovePasskey.tsx, packages/react-wallet-kit/src/components/user/UpdateEmail.tsx, packages/react-wallet-kit/src/helpers/index.tsx, packages/react-wallet-kit/src/index.css, packages/react-wallet-kit/src/providers/client/Provider.tsx
=> added passkey remove and add modal, and oauth remove modal

examples/with-sdk-js/src/app/page.tsx, packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/sdk-js/src/__clients__/core.ts, packages/sdk-js/src/__stampers__/wallet/base.ts, packages/sdk-js/src/__types__/base.ts, packages/sdk-js/src/utils.ts
=> add linked wallets to fetchWallets()

examples/react-wallet-kit/package.json, examples/react-wallet-kit/src/app/global.css, examples/react-wallet-kit/src/app/layout.tsx, examples/react-wallet-kit/src/app/page.tsx, examples/react-wallet-kit/src/providers/config/ConfigProvider.tsx, examples/react-wallet-kit/src/providers/config/Panel.tsx, examples/with-sdk-js/src/app/page.tsx, packages/react-wallet-kit/src/components/auth/Action.tsx, packages/react-wallet-kit/src/components/auth/OAuth.tsx, packages/react-wallet-kit/src/components/auth/Wallet.tsx, packages/react-wallet-kit/src/components/auth/index.tsx, packages/react-wallet-kit/src/components/user/LinkWallet.tsx, packages/react-wallet-kit/src/providers/client/Provider.tsx, pnpm-lock.yaml
=> Wallet kit demo and wallet linking UI

examples/with-sdk-js/src/app/page.tsx, packages/react-wallet-kit/src/index.ts, packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/sdk-js/src/__clients__/core.ts, packages/sdk-js/src/__types__/base.ts, packages/sdk-js/src/index.ts
=> fixed intellisense issues and type exporting

packages/react-wallet-kit/src/utils.ts, packages/sdk-js/src/__clients__/core.ts, packages/sdk-js/src/__stampers__/wallet/signer.ts, packages/sdk-js/src/__types__/base.ts, packages/sdk-js/src/utils.ts, packages/wallet-stamper/src/ethereum.ts, packages/wallet-stamper/src/solana.ts, packages/wallet-stamper/src/stamper.ts, packages/wallet-stamper/src/types.ts
=> add client side signing to signMessage 

packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/sdk-js/src/__clients__/core.ts
=> added jsdocs comments to all provider and core methods

examples/kitchen-sink/src/http/approveActivity.ts, examples/kitchen-sink/src/http/rejectActivity.ts, examples/kitchen-sink/src/sdk-server/approveActivity.ts, examples/kitchen-sink/src/sdk-server/rejectActivity.ts
=> add approval and rejection examples

packages/sdk-js/src/__clients__/core.ts
=> polishing js-doc comments

examples/react-wallet-kit/src/app/layout.tsx, examples/react-wallet-kit/src/app/page.tsx, examples/react-wallet-kit/src/components/Svg.tsx, examples/react-wallet-kit/src/components/demo/DemoPanel.tsx, examples/react-wallet-kit/src/components/demo/UserSettings.tsx, examples/react-wallet-kit/src/providers/config/ConfigProvider.tsx, packages/react-wallet-kit/src/index.css, packages/react-wallet-kit/src/providers/theme/Overrides.tsx
=> cleaned up hydration errors for mobile demo view

examples/react-wallet-kit/next.config.js, examples/react-wallet-kit/src/app/page.tsx, examples/react-wallet-kit/src/components/demo/DemoPanel.tsx, examples/react-wallet-kit/src/providers/config/ConfigProvider.tsx
=> more demo polish

examples/react-wallet-kit/package.json, examples/react-wallet-kit/src/components/demo/DemoPanel.tsx, examples/react-wallet-kit/src/utils.ts, packages/react-wallet-kit/src/components/sign/Message.tsx, packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/react-wallet-kit/src/providers/client/Types.tsx, packages/sdk-js/src/__clients__/core.ts, packages/sdk-js/src/utils.ts, pnpm-lock.yaml
=> sign message fix

examples/react-wallet-kit/src/app/layout.tsx, examples/react-wallet-kit/src/components/demo/DemoPanel.tsx, examples/react-wallet-kit/src/providers/config/Panel.tsx, examples/react-wallet-kit/src/utils.ts, packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/sdk-js/src/__clients__/core.ts, packages/sdk-js/src/__storage__/web/storage.ts
=> Fixed sign verification issue for connected wallets and session refresh bug

examples/with-sdk-js/src/app/layout.tsx, examples/with-sdk-js/src/app/page.tsx, packages/react-wallet-kit/src/components/auth/Wallet.tsx, packages/sdk-js/src/__clients__/core.ts, packages/sdk-js/src/__wallet__/web/connector/wallet-connect/base.ts, packages/sdk-js/src/__wallet__/web/manager.ts
=> wallet connect fixes

examples/with-sdk-js/src/app/page.tsx, packages/sdk-js/src/__clients__/core.ts, packages/sdk-js/src/__types__/base.ts, packages/sdk-js/src/__wallet__/web/connector/solana.ts, packages/sdk-js/src/utils.ts
=> solana signing cleanup

examples/react-wallet-kit/src/app/page.tsx, examples/react-wallet-kit/src/components/Disclosure.tsx, examples/react-wallet-kit/src/components/demo/DeleteSubOrgWarning.tsx, examples/react-wallet-kit/src/components/demo/DemoPanel.tsx, examples/react-wallet-kit/src/components/demo/UserSettings.tsx, examples/react-wallet-kit/src/providers/config/Panel.tsx, packages/react-wallet-kit/src/components/auth/Wallet.tsx
=> Demo styling

packages/core/src/__clients__/core.ts, packages/core/src/utils.ts
=> made email social linking a google accounts only thing

examples/react-wallet-kit/src/app/layout.tsx, examples/react-wallet-kit/src/components/Svg.tsx, examples/react-wallet-kit/src/components/Switch.tsx, examples/react-wallet-kit/src/components/demo/AuthButtons/AuthenticatorButton.tsx, examples/react-wallet-kit/src/components/demo/AuthButtons/EmailAuthButton.tsx, examples/react-wallet-kit/src/components/demo/AuthButtons/PhoneAuthButton.tsx, examples/react-wallet-kit/src/components/demo/AuthButtons/SocialButton.tsx, examples/react-wallet-kit/src/components/demo/AuthButtons/index.tsx, examples/react-wallet-kit/src/components/demo/DeleteSubOrgWarning.tsx, examples/react-wallet-kit/src/components/demo/DemoPanel.tsx, examples/react-wallet-kit/src/components/demo/UserSettings.tsx, examples/react-wallet-kit/src/providers/config/ConfigProvider.tsx, examples/react-wallet-kit/src/providers/config/Panel.tsx, examples/react-wallet-kit/src/utils.ts, packages/react-wallet-kit/src/components/auth/OAuth.tsx, packages/react-wallet-kit/src/providers/client/Provider.tsx
=> fixed comments made by bryce and andrew for demo

examples/react-wallet-kit/package.json, examples/react-wallet-kit/src/app/layout.tsx, examples/react-wallet-kit/src/constants.ts, packages/core/package.json, packages/core/src/__clients__/core.ts, packages/core/src/__stampers__/api/base.ts, packages/core/src/__stampers__/api/mobile/stamper.ts, packages/core/src/__stampers__/api/web/stamper.ts, packages/core/src/__stampers__/passkey/base.ts, packages/core/src/__types__/base.ts, packages/react-wallet-kit/package.json, packages/react-wallet-kit/src/components/auth/OTP.tsx, pnpm-lock.yaml
=> Resolved comments

pnpm-lock.yaml
=> fixed js build error

packages/react-wallet-kit/src/index.css
=> fixed issues with tailwind 3

packages/core/src/__types__/base.ts, packages/core/src/__wallet__/base.ts, packages/core/src/__wallet__/connector.ts, packages/core/src/__wallet__/mobile/manager.ts, packages/core/src/__wallet__/stamper.ts, packages/core/src/__wallet__/wallet-connect/base.ts, packages/core/src/__wallet__/wallet-connect/client.ts, packages/core/src/__wallet__/web/manager.ts, packages/core/src/__wallet__/web/native/ethereum.ts, packages/core/src/__wallet__/web/native/solana.ts
=> cleaup and address comments

examples/delegated-access/CHANGELOG.md, packages/cosmjs/CHANGELOG.md, packages/eip-1193-provider/CHANGELOG.md, packages/ethers/CHANGELOG.md, packages/http/CHANGELOG.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react/CHANGELOG.md, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/OtpVerification.tsx, packages/sdk-server/CHANGELOG.md, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts, packages/sdk-server/src/__types__/base.ts, packages/sdk-server/src/actions.ts, packages/solana/CHANGELOG.md, packages/viem/CHANGELOG.md, packages/viem/src/index.ts
=> merged with main

packages/react-wallet-kit/src/providers/client/Provider.tsx
=> chain listeners

.changeset/hot-baths-clean.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts
=> Synced with mono

packages/core/src/__types__/base.ts, packages/core/src/__wallet__/wallet-connect/base.ts, packages/core/src/__wallet__/wallet-connect/client.ts, packages/react-wallet-kit/src/providers/client/Provider.tsx
=> wallet connect listeners

examples/with-sdk-js/package.json, examples/with-sdk-js/src/app/page.tsx, packages/cosmjs/package.json, packages/cosmjs/src/index.ts, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/turnkey.ts, packages/ethers/package.json, packages/ethers/src/index.ts, packages/solana/package.json, packages/solana/src/index.ts, packages/viem/package.json, packages/viem/src/index.ts, pnpm-lock.yaml
=> Added viem and other support for new packages

packages/react-wallet-kit/src/providers/client/Provider.tsx
=> wrap functions in useCallbacks

examples/with-aave/.env.local.example, examples/with-aave/README.md, examples/with-aave/package.json, examples/with-aave/src/balance.ts, examples/with-aave/src/createPolicy.ts, examples/with-aave/src/deposit.ts, examples/with-aave/src/withdraw.ts, examples/with-aave/tsconfig.json, pnpm-lock.yaml
=> Adding a with-aave example

packages/sdk-browser/scripts/codegen.js, packages/sdk-server/scripts/codegen.js
Another regex needs to be changed context: #875 
local
N/A not public facing …
=> Update another regex

examples/react-wallet-kit/src/components/demo/DeleteSubOrgWarning.tsx, examples/react-wallet-kit/src/components/demo/DemoPanel.tsx, examples/react-wallet-kit/src/components/demo/SignatureVerification.tsx, examples/react-wallet-kit/src/components/demo/UserSettings.tsx, packages/react-wallet-kit/src/providers/client/Provider.tsx
=> sentence casing fixes

packages/core/src/utils.ts
=> fixed passkey validation on web

packages/core/src/utils.ts
=> fixed passkey name validation again

packages/sdk-types/scripts/codegen.js, packages/sdk-types/src/__generated__/types.ts
=> codegen fix

packages/core/src/__clients__/core.ts
=> fix comment headers for auth functions

packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/react-wallet-kit/src/types/base.ts
=> always open oauth in page for mobile

packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/react-wallet-kit/src/types/base.ts
=> fixed use callback dependency array

.changeset/tangy-geckos-wait.md, examples/react-wallet-kit/src/components/demo/DemoPanel.tsx, packages/react-wallet-kit/src/providers/modal/Root.tsx
=> fixed onClose not running for children pages

.changeset/cruel-readers-peel.md, packages/core/src/__types__/auth.ts, packages/core/src/__types__/enums.ts, packages/core/src/__types__/external-wallets.ts, packages/core/src/__types__/index.ts, packages/core/src/index.ts, packages/react-wallet-kit/src/index.ts
=> fix core types export in react-wallet-kit

.changeset/cool-boxes-roll.md, examples/with-sdk-js/src/app/layout.tsx, examples/with-sdk-js/src/app/page.tsx, packages/core/src/__clients__/core.ts, packages/core/src/__wallet__/web/native/solana.ts, packages/core/src/utils.ts
=> fixed wallet accounts limit & signing sol transactions with connected wallets

.changeset/spotty-cities-sleep.md, examples/with-sdk-js/e2e/fetch-methods.spec.ts, examples/with-sdk-js/e2e/helpers/selectors.ts, examples/with-sdk-js/src/app/layout.tsx, examples/with-sdk-js/src/app/page.tsx, packages/core/scripts/codegen.js, packages/core/src/__clients__/core.ts, packages/core/src/__generated__/sdk-client-base.ts, packages/core/src/__types__/config.ts, packages/core/src/__types__/method-types.ts, packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/react-wallet-kit/src/types/base.ts
Mostly to allow passkey stamping with `@turnkey/viem`, `@turnkey/ethers`, etc.
yes and new playwright added
yes
=> defaultStamperType and createHttpClient added

.changeset/plain-dancers-draw.md, packages/viem/src/index.ts
=> fixed signAuthorization return type
