examples/with-gnosis/README.md, examples/with-gnosis/src/index.ts, packages/ethers/src/__tests__/index-test.ts, packages/ethers/src/index.ts
- Add support for signing typed data (per EIP-712) to Turnkey Ethers implementation
- Update Gnosis example to make use of offchain signatures, with two flavors: (1) using signed typed data, and (2) using raw message signing, in addition to the standard onchain flow
- Unit
- Testnet
Some helpful documentation/references:
- https://github.com/ethers-io/ethers.js/issues/830
- https://ethereum.stackexchange.com/questions/117631/as-in-web3-js-get-the-same-signature-as-the-signature-from-the-signtypeddata-v4
- Not relevant for JS/TS implementations, but noting some gotchas around encoding:
- https://ethereum.stackexchange.com/questions/137491/inconsistency-in-recovered-account-when-verifying-eip-712-javascript-python
- https://ethereum.stackexchange.com/questions/125425/solidity-cannot-verify-e …
=> add signTypedData to ethers implementation

packages/ethers/src/__tests__/index-test.ts, packages/http/src/__tests__/request-test.ts, packages/http/src/base.ts, packages/http/src/shared.ts
Adds a details field to the error that is thrown when a request to turnkey returns an error code.
These aren't typed at the moment. Any ideas on the best way to do/expose this?
Unit
=> Returns details as part of error

.codesandbox/ci.json, package.json
https://codesandbox.io/docs/learn/sandboxes/ci
> Whenever a Pull Request is opened it builds a version of the library from that PR. This is published to our registry, so you can immediately test the library in CodeSandbox or locally without publishing to npm or elsewhere.
You shouldn't use these adhoc builds for anything serious, but they're great for quickly verifying changes / fixes.
For instance, say you want to test `http` and `ethers`. For the builds generated by this PR, you can use them via:
```bash
$ npm install https://pkg.csb.dev/tkhq/sdk/commit/2492405d/@turnkey/ethers https://pkg.csb.dev/tkhq/sdk/commit/2492405d/@turnkey/http
```
or in your `package.json`:
```json
{
"dependencies": {
"@turnkey/ethers": "https://pkg.csb.dev/tkhq/sdk/commit/2492405d/@turnkey/ethers", …
```
=> Add codesandbox CI adhoc build config

.changeset/2023-06-14-sync-protos.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json
Releasing:
* `@turnkey/http@0.17.0`
* `@turnkey/ethers@0.16.0`
* `@turnkey/cosmjs@0.4.0`
```
$ corepack enable && pnpm install -r
$ pnpm run clean-all && pnpm run build-all
$ pnpm publish -r --dry-run --no-git-checks
```
...and CI!
=> Release packages (2023-06-21)

.codesandbox/ci.json, .gitignore, README.md, examples/with-viem/.env.local.example, examples/with-viem/.npmrc, examples/with-viem/README.md, examples/with-viem/package.json, examples/with-viem/src/index.ts, examples/with-viem/tsconfig.json, package.json, packages/viem/.env.example, packages/viem/.npmrc, packages/viem/LICENSE, packages/viem/README.md, packages/viem/jest.config.js, packages/viem/package.json, packages/viem/src/__tests__/index-test.ts, packages/viem/src/index.ts, packages/viem/tsconfig.json, packages/viem/tsconfig.typecheck.json, pnpm-lock.yaml, tsconfig.mono.json
This PR introduces a new `@turnkey/viem` package with (for now) a single helper function to create a Viem Custom Account backed by a Turnkey API key. I'll work on making a helper to work with passkeys next, this is a warmup!
The associated `with-viem` example demonstrates sending a transaction on Sepolia using this new helper. It works 🎉 
A problem I ran into: `viem` expects typescript >5.1 (for cutting edge typing features) and node >18 (for `fetch`). Does that mean we need to upgrade all of our packages? I tried to mandate this only in the new packages, but there are warnings when running `typecheck` now:
```
examples/with-viem                       |  WARN  Unsupported engine: wanted: {"node":">=18.0.0"} (current: {"node":"v16.16.0","pnpm":"8.4.0"})
packages/viem …
```
=> New viem package + example

examples/deployer/.env.local.example, examples/rebalancer/.env.local.example, examples/sweeper/.env.local.example, examples/trading-runner/.env.local.example, examples/with-cosmjs/.env.local.example, examples/with-ethers/.env.local.example, examples/with-gnosis/.env.local.example, examples/with-nonce-manager/.env.local.example, examples/with-solana/.env.local.example, examples/with-solana/src/createSolanaKey.ts, examples/with-uniswap/.env.local.example
There are two small fixes in this PR.
1. [Recent examples](https://github.com/tkhq/sdk/blob/bbbe31ff764cc356f6af357de5c343db27467f8a/examples/with-viem/.env.local.example#L3) use `https://api.turnkey.com` as the API base URL. 965c8897200beebf155c55b99c4de3576c6208f3 updates all the example env files to use it.
2. The Solana example contains a bug that causes it to fail after creating a private key. It's caused by the type of call being `ACTIVITY_TYPE_CREATE_PRIVATE_KEYS_V2` and the result that is read from being `createPrivateKeysResult`, presumbly the V1 API. 076c201fcc8f10fc7868087ac9e94b8505e6fbe2 fixes this.
I ran the Solana example project, but otherwise haven't tested this.
=> Minor fixes to env files and Solana example

examples/with-federated-passkeys/.env.local.example, examples/with-federated-passkeys/src/pages/api/subOrg.ts, examples/with-federated-passkeys/src/pages/index.tsx, examples/with-viem-and-passkeys/.env.local.example, examples/with-viem-and-passkeys/src/pages/api/subOrg.ts, examples/with-viem-and-passkeys/src/pages/index.tsx
This updates the federated passkey example to include a login button. Despite the example being stateless, we login by using the updated `whoami` endpoint which now allows lookups for sub-orgs using the parent-org ID + WebAuthN stamp.
I developed this against staging. Note the `whoami` endpoint updates have not been deployed to production yet so we should wait until that happens.
=> federated/viem passkey: Add login button leveraging updated Whoami endpoint

examples/with-viem/package.json, examples/with-viem/src/advanced.ts, examples/with-viem/src/index.ts, examples/with-viem/src/util.ts, packages/viem/CHANGELOG.md, packages/viem/package.json, packages/viem/src/index.ts
Address https://github.com/tkhq/sdk/issues/116 🛠️👷 
Note: setting up the e2e tests viem will be pulled into a separate PR.
Note/interesting observation:
```node
const recoveredAddress = await recoverMessageAddress({
message,
signature: signMessageSignature,
});
```
When running in the context of a (Go) test harness, this would result in segfaults. Wild! The same was happening for `verifyMessage`, until it was prepended with the wallet client (i.e. `walletClient.verifyMessage({})`). Guessing there's some internals stuff going on with regards to having a (connected) client?
ran the scripts!
https://github.com/wagmi-dev/wagmi/discussions/2340
=> update viem signing

examples/with-federated-passkeys/src/pages/index.tsx
Added an additional algorithm that is now supported, and added new authenticatorSelection parameters to support android based passkeys that do not support discoverable credentials 
Discussed with Max and tested locally that I am able to create and use a passkey with an android phone
=> Update federated passkey demo

package.json, packages/api-key-stamper/package.json, packages/api-key-stamper/tsconfig.esm.json, packages/cosmjs/package.json, packages/cosmjs/tsconfig.esm.json, packages/ethers/package.json, packages/ethers/tsconfig.esm.json, packages/http/package.json, packages/http/tsconfig.esm.json, packages/iframe-stamper/package.json, packages/iframe-stamper/tsconfig.esm.json, packages/viem/package.json, packages/viem/tsconfig.esm.json, packages/webauthn-stamper/package.json, packages/webauthn-stamper/tsconfig.esm.json
=> chore: add esm to package dist

packages/webauthn-stamper/CHANGELOG.md, packages/webauthn-stamper/package.json
New version of webauthn-stamper for ESM support (#154)
=> Release new version of `@turnkey/webauthn-stamper`

packages/api-key-stamper/CHANGELOG.md, packages/api-key-stamper/package.json
We never released api-key-stamper after merging #154. This PR fixes this.
=> Release turnkey/api-key-stamper@v0.2.0

packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
In #166 I released `@turnkey/api-key-stamper` but forgot to bump all the dependent packages. This PR fixes this.
=> Release rest of packages after api-key-stamper v0.2.0 release

.github/pull_request_template.md
People forget/don't know how to update the change set when making changes to sdk. This PR adds instructions to the PR template that explains how to update the changeset.
NA; docs
=> Add change set instructions to PR template

.changeset/quiet-eyes-work.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/universal.ts, packages/viem/CHANGELOG.md, packages/viem/package.json, packages/webauthn-stamper/CHANGELOG.md, packages/webauthn-stamper/package.json, packages/webauthn-stamper/src/universal.ts
I think #174 broke universal files? Or rather, universal files were never written to work well with modules since they use `require`.
When running the federated passkey demo, the following error happens as a result:
TODOs:
=> Stop using `require` in universal files

.changeset/breezy-kangaroos-pay.md, examples/with-federated-passkeys/src/pages/index.tsx, packages/webauthn-stamper/package.json, packages/webauthn-stamper/src/index.ts, pnpm-lock.yaml
Bug discovered by @SimonVillage in https://github.com/tkhq/demo-passkey-wallet/issues/3: on ios/safari, cancelling the passkey prompt results in subsequent prompts automatically failing. The reason why: ios is stricter than other browsers when deciding whether a passkey prompt can be triggered or not. [This blog post](https://fy.blackhats.net.au/blog/2020-08-12-user-gesture-is-not-detected-using-ios-touchid-with-webauthn-rs/) has more information on this, but TL;DR: you need to have a maximum of one async promise between a user gesture (tap, click) and the code triggering a passkey prompt.
In our SDK we use [`crypto.subtle.digest`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest) to compute the SHA256 of the message to sign: …
=> Switch sha256 to be synchronous in `@turnkey/webauthn-stamper`

.changeset/quick-buttons-cross.md, .changeset/unlucky-doors-serve.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/iframe-stamper/CHANGELOG.md, packages/iframe-stamper/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> update packages for release v2023.12.0

examples/email-auth/src/components/Auth.tsx, examples/email-recovery/src/components/Recovery.tsx, examples/wallet-export/src/components/Export.tsx, examples/wallet-export/src/pages/index.module.css, examples/wallet-export/src/pages/index.tsx, packages/iframe-stamper/CHANGELOG.md, packages/iframe-stamper/README.md, packages/iframe-stamper/src/__tests__/iframe-test.ts, packages/iframe-stamper/src/index.ts
* Use container element instead of id for iframe stamper constructor. This allows for the iframe stamper to be appended onto an element in the shadow DOM.
* Update auth, recovery, export examples.
* Bump `turnkey/iframe-stamper` package major version.
* locally ran auth, recovery, export examples
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the command) along with the …
=> pass container element to iframe stamper

packages/iframe-stamper/package.json
Dry-run build.
TODO: Release package. …
=> bump iframe-stamper package to 1.0.0

.changeset/itchy-elephants-wave.md, packages/http/package.json, packages/http/src/index.ts, packages/http/src/version.ts
This is step 1 for us to send a header containing @turnkey/http's version when it fetches content from our public API! After that I'll use this new constant inside of the generated client to add a new `X-Version` header containing this value.
I figured this constant is useful on its own: other packages (or apps) may want to use that for debugging purposes.
The idea for the preinstall script is taken straight from [stack overflow](https://stackoverflow.com/questions/41123631/how-to-get-the-version-from-the-package-json-in-typescript)
=> Export http package version

.changeset/proud-swans-deny.md, packages/http/package.json, packages/http/src/version.ts
I think it'll be useful to have the package name in here instead of just a version. Maybe later we'll end up having multiple SDKs with overlapping versions!
Proof is in the pudding: running pnpm i regenerated the version string.
Yes ✅
=> Add package name to version string

.changeset/small-flowers-serve.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/index.ts, packages/http/src/version.ts, packages/viem/CHANGELOG.md, packages/viem/package.json
Because of the preinstall script introduced in #186 and #187 we're seeing failures to install from npm:
```
npm ERR! command failed
npm ERR! command sh -c node -p "'export const VERSION = ' + JSON.stringify(require('./package.json').name + '@' + require('./package.json').version) + ';'" > src/version.ts
npm ERR! sh: src/version.ts: No such file or directory
```
This PR reverts the two PRs, we'll re-introduce this at a later time!
=> Revert version export for @turnkey/http (release fix)

.github/workflows/js-build.yml
added preprod E2E tests as a completely separate check. preprod checks should not be required for merging; after all, there's a chance someone is testing on preprod, and these CI tests become a red-herring.
otherwise, it's a nice to have to check for regressions before rolling to prod.
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the command) along with the type of …
=> add preprod testing to CI

.changeset/hungry-otters-destroy.md, packages/solana/package.json, packages/solana/src/__tests__/index-test.ts, packages/solana/src/index.ts, pnpm-lock.yaml
- Give sign message functionality to solana turnkey wallets
- Manually tested using the unit test and hard coded api keys
- yes
These changes will be used at release time to determine what packages to publish …
=> implement signMessage on Solana TurnkeySigner

internal/jest-config/package.json, internal/jest-config/transformer.js, packages/react-native-passkey-stamper/jest.config.js, pnpm-lock.yaml
1) Add preset for react native in jest config
2) Handle Flow type annotations …
=> fix jest issue with react native passkey stamper

packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
Update to v2024.2.0
The only user-facing change is `number` (new) vs `string` (previously) for `mnemonicLength`.
Added a changeset and bumped versions accordingly.
=> Update swagger and generated types to v2024.2.0

.changeset/sweet-dolphins-agree.md, packages/solana/src/__tests__/index-test.ts, packages/solana/src/index.ts
Support versioned transactions. Also addresses this https://github.com/tkhq/sdk/issues/215
Unit test and manually sent a versioned transaction that was signed by the turnkey testing wallet
https://solscan.io/tx/2pbRDh5wAAxvVPhm432gQVYNaNeWdUZ3UMP7rrKyBBURiFcGHWqhEU18hgNoSRSRkmYA2w4518gnnWQbKSNfRCXv?cluster=devnet
Yes
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the …
=> add support for signing solana versioned transactions

.changeset/polite-eagles-press.md, packages/iframe-stamper/src/index.ts
Add optional `keyFormat` (options are `HEXADECIMAL` [default] and `SOLANA`) and `publicKey` parameters to `injectKeyExportBundle`. Add `extractKeyEncryptedBundle`.
Cannot be released until https://github.com/tkhq/frames/pull/27 is merged and released.
WIP! Testing with local import.turnkey.com
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the command) along with the …
=> Apply key formatting

.changeset/eight-ants-tease.md, .changeset/polite-eagles-press.md, packages/iframe-stamper/CHANGELOG.md, packages/iframe-stamper/package.json, packages/iframe-stamper/src/index.ts
Remove `publicKey` param from `injectKeyExportBundle` now that export.turnkey.com can derive it. (https://github.com/tkhq/frames/pull/28, https://github.com/tkhq/frames/pull/29)
Ran local example for importing and exporting private keys.
Yes …
=> Remove public key param for key export

packages/http/README.md
Something small I noticed when going through the SDK docs -- it's a bit confusing here because the variable that is initialized in the docs is the `client` but then the API call is being made from a variable called `TurnkeyAPI` which isn't initialized anywhere in the README.
My best guess is this is an outdated? way of calling the API and is easier to understand if we are consistent and show the API being called through the instantiated http client. 
Feel free to reject if this is wrong and the client in the README is supposed to be `TurnkeyAPI` @r-n-o @andrewkmin
=> Quick Docs Fix

.changeset/chilled-shirts-lay.md, examples/wallet-import-export/src/components/ExportWallet.tsx, examples/wallet-import-export/src/components/ImportWallet.tsx, examples/wallet-import-export/src/pages/index.tsx, packages/iframe-stamper/src/index.ts
Addresses ToB findings from ENG-1447 and ENG-1497. Pass the expected  metadata (organization id and user id) to the iframe via the iframe stamper, so the iframe can verify the enclave signature and that that expected metadata matches the metadata contained in the `importBundle` and `exportBundle`.
Part 1a: https://github.com/tkhq/sdk/pull/233
Part 1b:  https://github.com/tkhq/frames/pull/33
Part 1c: https://github.com/tkhq/go-sdk/pull/47
Part 2: https://github.com/tkhq/tkcli/pull/59
Part 3: https://github.com/tkhq/mono/pull/2806
tested using the wallet-import-example and local import.turnkey.com and local export.turnkey.com
yes (to `iframe-stamper` package)
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm …
=> Part 1a/3: Verifiable metadata

packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/sdk-browser/scripts/codegen.js, packages/sdk-browser/src/__generated__/sdk-client-base.ts, packages/sdk-browser/src/__generated__/sdk_api_types.ts, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-browser/src/__types__/base.ts, packages/sdk-browser/src/models.ts, packages/sdk-browser/src/sdk-client.ts, packages/sdk-react/src/contexts/TurnkeyContext.tsx, packages/sdk-server/src/__generated__/sdk-client-base.ts, packages/sdk-server/src/__generated__/sdk_api_types.ts, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts
Create a login fxn that uses the new read only session creation activity …
=> support login management using new readonly endpoint

packages/sdk-browser/src/index.ts, packages/sdk-browser/src/turnkey-helpers.ts, packages/sdk-server/src/index.ts, packages/sdk-server/src/turnkey-helpers.ts
Adds default helpers for generating a walletAccount at index and exports the initial configuration as a constant
=> export DEFAULT_ETHEREUM_ACCOUNT helpers from sdk packages

.changeset/five-terms-march.md, examples/wallet-import-export/src/components/Import.tsx, examples/wallet-import-export/src/components/ImportWallet.tsx, packages/iframe-stamper/src/index.ts
ENG-1388. Adds `applySettings` method to the iframe stamper that allows custom settings for surface-level/UI components in the iframe (styles, supported mnemonic lengths, supported private key formats, extra validation, etc.). The first setting we're implementing is `styles`, where CSS styles can be validated, sanitized, and applied to a specific HTML element on import.turnkey.com.
Relevant to https://github.com/tkhq/frames/pull/34
using wallet-import-export example against the old and new local instances of import.turnkey.com
yes to `iframe-stamper` package
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write …
=> Apply settings via iframe-stamper

examples/rebalancer/src/index.ts, examples/rebalancer/src/requests/createActivityApproval.ts, examples/rebalancer/src/requests/createActivityRejection.ts, examples/rebalancer/src/requests/createPolicy.ts, examples/rebalancer/src/requests/createPrivateKey.ts, examples/rebalancer/src/requests/createPrivateKeyTag.ts, examples/rebalancer/src/requests/createUser.ts, examples/rebalancer/src/requests/createUserTag.ts, examples/rebalancer/src/requests/getActivities.ts, examples/rebalancer/src/requests/getActivity.ts, examples/rebalancer/src/requests/getPrivateKeysForTag.ts, packages/sdk-browser/src/index.ts, packages/sdk-browser/src/sdk-client.ts, packages/sdk-react/src/contexts/TurnkeyContext.tsx, packages/sdk-server/README.md, packages/sdk-server/src/__tests__/request-test.ts, packages/sdk-server/src/__types__/base.ts, packages/sdk-server/src/index.ts, packages/sdk-server/src/sdk-client.ts
Can see the end-result from the PR to `demo-embedded-wallet` https://github.com/tkhq/demo-embedded-wallet/pull/10
=> changes top-level naming of sdk exports to clients

packages/sdk-browser/src/sdk-client.ts
Removes the need to manually pass the `organizationId` into a call for the `currentUserSession()` as it will now infer it automatically
See the associated code change to the `demo-embedded-wallet` here: https://github.com/tkhq/demo-embedded-wallet/pull/12
=> Use the organizationId of the currentUser by default when using readOnlySessions so you don't need to manually pass it in

.changeset/silent-rocks-cry.md, examples/with-ethers/README.md, examples/with-ethers/package.json, examples/with-ethers/src/index.ts, examples/with-viem/README.md, examples/with-viem/package.json, examples/with-viem/src/index.ts, packages/ethers/package.json, packages/ethers/src/index.ts, packages/sdk-browser/package.json, packages/viem/package.json, packages/viem/src/index.ts, pnpm-lock.yaml
considerations: viem / ethers become a tiny bit heavier
TODO:
- replace all instances of goerli with sepolia
- test both (update demo-viem-passkeys and demo-ethers-passkeys)
- ran examples
These changes will …
=> update ethers + viem types

packages/sdk-browser/src/__polyfills__/window.ts, packages/sdk-browser/src/sdk-client.ts, packages/sdk-browser/src/storage.ts
This PR adds a polyfill to reference the window object through in the browser-sdk. The polyfill will render a mock object if the browser-sdk happens to be rendered in a server environment.
The browser-sdk usually should not be rendered in a server environment, but there are apparently next.js flows that make this possible, so this enables those flows to function correctly.
=> Polyfill Window object on Browser SDK

packages/sdk-browser/src/__types__/base.ts, packages/sdk-browser/src/sdk-client.ts, packages/sdk-react/src/contexts/TurnkeyContext.tsx
This is to remove the iframeUrl config variable from the TurnkeyBrowser config, and have full customization over how the `iframeClient` is init
=> Updated iFrame Client Syntax

packages/crypto/src/__tests__/crypto-test.ts, packages/crypto/src/crypto.ts, packages/crypto/src/math.ts
- move math-related utils to `math.ts`
- rename + rearrange some functions
- add `extractPrivateKeyFromPKCS8Bytes`, specifically for use in https://github.com/tkhq/sdk/pull/282. This is required because exporting private keys using webcrypto is only supported by the `pkcs8` format; you can't export using `raw`. As a result, we have to do some manual manipulation to get the 32-byte "actual" private key out of the pkcs8 envelope
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8 …
=> add utils and rearrange @turnkey/crypto

packages/crypto/src/__tests__/crypto-test.ts, packages/crypto/src/crypto.ts
=> use public key

packages/sdk-browser/package.json, packages/sdk-browser/src/models.ts, packages/sdk-browser/src/sdk-client.ts, packages/sdk-browser/src/storage.ts, packages/sdk-browser/src/utils.ts, packages/sdk-react/src/contexts/TurnkeyContext.tsx, pnpm-lock.yaml
See iteration cycles on https://replit.com/@andrew306/RepulsiveRundownObject#index.ts
This flavor of creating passkey sessions assumes that you've created the suborg already and know their suborg ID.
This does not encapsulate logic to, say, create a new suborg and have a fresh passkey session for them out of the gate. However, the abstraction is there: you could call `createEmbeddedAPIKey`, grab the resulting public key and include it as a user's API key within a `CreateSubOrganization` call.
Note that this depends on `hpke-js` which is not available in some environments (such as react native). We'll have to do some followup work there to get native support at a later time.
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm …
=> enable passkey sessions

packages/sdk-browser/src/sdk-client.ts
removes the auth bundle from localstorage when "logoutUser" is called to prevent issues where a user is logged in with another user's signing auth bundle
=> remove auth bundle on logout

.changeset/pink-roses-wait.md, packages/viem/src/index.ts
Ported from [forked PR](https://github.com/tkhq/sdk/pull/298) by @matt-mertens 
Would like to utilize the existing viem account functions but want to create our own custom viem account abstraction object
N/A
yes 
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the command) along with the type of [semver change (major.minor.patch)](https://semver.org/) (which you should …
=> Export @turnkey/viem signing functions

packages/crypto/README.md, packages/crypto/src/__tests__/crypto-test.ts, packages/crypto/src/crypto.ts
We got decryption so we may as well have encryption! Afaik, nothing really out there that supports e2e hpke decryption and encryption that can be used with any runtime, so why not :)
These changes will be …
=> Moe/add hpke encryption 

.changeset/nice-taxis-smash.md, packages/api-key-stamper/src/tink/elliptic_curves.ts, packages/api-key-stamper/src/utils.ts, packages/encoding/src/__tests__/index-test.ts, packages/encoding/src/index.ts, packages/http/src/webauthn-json/base64url.ts
$title
There are cases where we want to manually pad buffers to get to a certain length, primarily when we're dealing with jwks. 
The nature of this change is similar in spirit to another change we recently rolled out for our iframes: https://github.com/tkhq/frames/pull/44
Unit, smoke via https://github.com/tkhq/sdk/pull/322
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added …
=> padding fixes

.gitignore, examples/with-sdk-server/README.md, examples/with-sdk-server/config.json.example, examples/with-sdk-server/package.json, examples/with-sdk-server/src/index.ts, examples/with-sdk-server/tsconfig.json, packages/sdk-server/README.md, pnpm-lock.yaml
Simple example to show how one can use `@turnkey/sdk-browser` to make API calls. Nothing fancy, but could be a good base for node scripts using the Turnkey API.
Bonus: spotted and fixed a mistake in the sdk-browser package README :)
Ran the new example.
=> Simple `@turnkey/sdk-server` example

packages/sdk-browser/src/sdk-client.ts
Users were unable to export keys in Solana format through our sdk prior to this …
=> Add key format to inject key export bundle

.changeset/twenty-flies-own.md, packages/sdk-browser/src/sdk-client.ts
$title. We were missing the ability to override `authenticatorAttachment`. Corresponding context can be found here: https://docs.turnkey.com/passkeys/options#authenticatorattachment
These changes will be used …
=> add additional passkey configs

.changeset/popular-rats-dance.md, packages/sdk-browser/src/index.ts
There are times where a developers may want to manage the local storage of the users, sessions and auth bundles themselves. When implementing the demo-embeded-wallet I found that I needed to store the current session after creating a new sub organization. Without this, you need to call one of the `login` functions such as `passkeyClient.login()` in order to save the session to local storage. However, this would require an additional passkey tap.
This would allow for creating a session for a new sub org using the parent org and then saving the session in local storage.
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you …
=> Exposes the storage APIs for the sdk-browser

.changeset/hip-turtles-cheat.md, packages/sdk-browser/src/sdk-client.ts
This simplifies code that looks like:
```ts
//@ts-ignore
authIframeClient.config.organizationId = user?.organizationId;
const session = await authIframeClient?.login();
```
...into something like:
```ts
const session = await authIframeClient?.login(user?.organizationId);
```
No test yet but it's a pretty trivial change
Yes.
=> Allow org id override for `TurnkeyBrowserClient.login`

examples/with-aptos/src/index.ts, examples/with-sui/src/index.ts
- Increase gas budget for SUI
- Sender creates onchain account for APTOS if it doesn't already exist
These changes will be used at release time to determine what packages to publish and how to bump their …
=> Quick fix for aptos and sui examples

.changeset/lemon-baboons-dress.md, packages/eip-1193-provider/src/index.ts
`personal_sign` function parameters are flipped incorrectly, the first parameter is the data to be signed and the second parameter is the address, this fixes that.
These changes will be used at release time …
=> Fix `personal_sign` parameters

.changeset/lemon-baboons-dress.md, packages/eip-1193-provider/src/__tests__/index.test.ts, packages/eip-1193-provider/src/index.ts
Submitted by @k-xo 🙌, fixes the personal-sign function which has flipped parameters from the eth-sign function
These changes will be used at release time to determine what packages to publish and how to bump …
=> Fix personal sign parameter

examples/with-solana/src/jupiterSwap.ts, examples/with-solana/src/utils/retrySender.ts
$title
locally ran `pnpm run jupiter-swap` …
=> make solana broadcasting script more resilient

examples/export-in-node/package.json, examples/export-in-node/src/index.ts, examples/import-in-node/package.json, examples/import-in-node/src/index.ts, examples/with-aptos/package.json, examples/with-aptos/src/index.ts, examples/with-offline/package.json, examples/with-offline/src/index.ts, examples/with-solana/package.json, examples/with-solana/src/addSignature.ts, examples/with-solana/src/advanced.ts, examples/with-solana/src/faucet.ts, examples/with-solana/src/index.ts, examples/with-solana/src/tokenTransfer.ts, examples/with-solana/src/utils/handleActivityError.ts, examples/with-solana/src/withFeePayer.ts, examples/with-sui/package.json, examples/with-sui/src/index.ts, pnpm-lock.yaml
This PR changes it so that we use the `prompts` library instead of `inquirer/prompts` for consistency with our stackblitz examples -- since it seems friendlier to be used with `pnpm` or `npm`
Tested the edited examples locally
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the command) along with the type of [semver change (major.minor.patch)](https://semver.org/) …
=> Change Inquirer/prompts dependency to prompts

examples/with-eth-passkeys-galore/src/pages/index.tsx, examples/with-solana-passkeys/src/pages/index.tsx
This PR fixes issues in examples `with-solana-passkeys` and `with-eth-passkeys-galore` where a passkey client makes sign requests with the orgID of the parent org and not the suborg
ran examples locally
These …
=> Fix SubOrgID issue with Passkey Examples

.changeset/odd-chefs-whisper.md, packages/sdk-browser/src/sdk-client.ts
Turnkey has long been supporting both ES256 and RS256. This is a spot that was missed. Of course users can override `pubKeyCredParams` if they so desire, but by default we should support RS256. RSA is used for e.g. Windows Hello passkeys.
✅
=> Support RS256 by default in `createUserPasskey`

examples/with-eth-passkeys-galore/.env.local.example, examples/with-eth-passkeys-galore/CHANGELOG.md, examples/with-eth-passkeys-galore/README.md, examples/with-eth-passkeys-galore/package.json, examples/with-eth-passkeys-galore/src/pages/index.tsx, examples/with-solana-passkeys/src/pages/index.tsx, pnpm-lock.yaml
=> add biconomy aa support to eth passkeys example

.changeset/wicked-impalas-relax.md, packages/sdk-browser/src/sdk-client.ts
This looks like an oversight. We allow for RPID override but do not let users customize timeout/userVerification/allowCredentials.
=> Allow overriding WebauthnStamper config when creating a passkey client

.changeset/itchy-jeans-try.md, packages/solana/src/index.ts
$title
extension of https://github.com/tkhq/sdk/pull/423 …
=> add optional organization id override for all methods

examples/with-eth-passkeys-galore/src/pages/api/createSubOrg.ts, packages/sdk-browser/src/turnkey-helpers.ts, packages/sdk-server/src/turnkey-helpers.ts
=> Add full coverage of default accounts in our sdk for all address formats

packages/telegram-cloud-storage-stamper/CHANGELOG.md, packages/telegram-cloud-storage-stamper/README.md, packages/telegram-cloud-storage-stamper/package.json, packages/telegram-cloud-storage-stamper/src/index.ts
Telegram Cloud storage does not allow for the `@` or `/` signs in cloud storage keys, so change the default key to conform to those standards.
These changes will be used at release time to determine what …
=> Update default cloud storage key

.changeset/curly-eyes-cover.md, packages/crypto/src/turnkey.ts
We have this functionality in our iframe stamper but not in our 'crypto' helper functions
These changes will be used at release time to determine what packages to publish and how to bump their version. For …
=> Solana export support for decryptExportBundle fxn

.changeset/wicked-frogs-prove.md, packages/telegram-cloud-storage-stamper/CHANGELOG.md, packages/telegram-cloud-storage-stamper/package.json, packages/telegram-cloud-storage-stamper/src/index.ts
=> Export the default tg cloud storage api key location

.changeset/silent-snails-carry.md, packages/sdk-react/src/components/auth/TurnkeyThemeProvider.tsx
Also added use client directive to the TurnkeyThemeProvider …
=> Changeset: UI components

.changeset/cuddly-starfishes-own.md, packages/sdk-react/package.json, packages/sdk-react/rollup.config.mjs, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/PhoneInput.css, packages/sdk-react/src/components/auth/PhoneInput.tsx, packages/sdk-react/src/index.ts, pnpm-lock.yaml
After importing `import '@turnkey/sdk-react/styles';` in the `layout.tsx` file and running `npm run dev`, an error occurred. When bundling CSS with Rollup using `rollup-plugin-postcss`, `@import` rules are not being correctly placed at the top of the final CSS bundle. This violates CSS specifications, which require `@import` statements to precede all other rules (except `@charset` and `@layer`).
Add `postcss-import` plugin to the PostCSS configuration to the Rollup setup.
The `postcss-import` plugin processes `@import rules` and ensures they appear at the top of the CSS file. By including this in the PostCSS plugins array, all `@import` rules are handled correctly before other CSS rules are processed, preventing build errors.
```bash
@import rules must precede all rules aside from …
```
=> Adds postcss-import plugin + fixes import for react phone styles

.changeset/cuddly-starfishes-own.md, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json
=> sdk-react release Dec 19: css bundling issue fix

examples/with-wallet-stamper/next.config.mjs, examples/with-wallet-stamper/src/env.mjs, package.json, packages/api-key-stamper/rollup.config.mjs, packages/cosmjs/rollup.config.mjs, packages/crypto/rollup.config.mjs, packages/eip-1193-provider/rollup.config.mjs, packages/encoding/rollup.config.mjs, packages/ethers/rollup.config.mjs, packages/http/rollup.config.mjs, packages/iframe-stamper/rollup.config.mjs, packages/react-native-passkey-stamper/rollup.config.mjs, packages/sdk-browser/rollup.config.mjs, packages/sdk-react/rollup.config.mjs, packages/sdk-server/rollup.config.mjs, packages/solana/rollup.config.mjs, packages/telegram-cloud-storage-stamper/rollup.config.mjs, packages/viem/rollup.config.mjs, packages/wallet-stamper/rollup.config.mjs, packages/webauthn-stamper/rollup.config.mjs, rollup.config.base.mjs
=> Add mjs to prettier config

.changeset/red-carrots-carry.md, packages/api-key-stamper/src/tink/elliptic_curves.ts, packages/api-key-stamper/src/utils.ts, packages/sdk-browser/src/utils.ts
Update a common error message that provides little info as to the root cause …
=> Update common error message

.changeset/old-schools-lick.md, packages/sdk-react/rollup.config.mjs, packages/sdk-react/src/components/auth/PhoneInput.module.css, packages/sdk-react/src/components/auth/PhoneInput.tsx, packages/sdk-react/src/index.ts
=> Fix css bundling issue with sdk-react

.changeset/beige-swans-build.md, examples/react-components/src/app/dashboard/dashboard.css, examples/react-components/src/app/index.css, packages/sdk-react/src/components/auth/Auth.module.css, packages/sdk-react/src/components/auth/Socials.module.css, packages/sdk-react/src/components/auth/TurnkeyThemeProvider.tsx, packages/sdk-react/src/components/export/Export.module.css, packages/sdk-react/src/components/import/Import.module.css, packages/sdk-react/src/components/theme.css
- Fonts now apply to all components, including MUI
- All components inherit font applied to the 'body' of the page
- Removed unnecessary font applications
These changes will be used at release time to …
=> Font inheritance fix allowing for customization

.changeset/long-baboons-boil.md, packages/iframe-stamper/src/index.ts
$title
iframe counterpart: https://github.com/tkhq/frames/pull/59
This mainly serves the case where there are concurrent, or serial, requests. Request IDs are used to disambiguate between multiple requests.
Latency implications: roughly ~4 seconds for 100 parallel signing requests, compared to ~0.7 seconds if signing 100 payloads using an im-memory API key stamper. The difference comes in overhead cost of the iframe communications.
- email auth example (https://github.com/tkhq/sdk/pull/468)
- tested for backwards compatibility as well
- yes
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly …
=> add request ids to iframe stamper

.github/actions/js-setup/action.yml, .github/workflows/js-build.yml
As of Feb 1, 2025 specific versions of `actions/cache` will be deprecated. Their [docs](https://github.com/actions/cache/releases/tag/v4.2.0) recommend using either the v4.2.0 or v3.4.0 GitHub SHA if you are using pinned versions in your workflows. …
=> chore: update GitHub Action SHAs

packages/crypto/src/math.ts, packages/crypto/src/turnkey.ts
- Improved efficiency by adding `% p` in modPow to ensure calculations remain within a smaller range. This reduces unnecessary large number computations
- Small comment fix that didn't make sense to me
These …
=> make modPow more efficient

.github/actions/js-setup/action.yml
- `set-output` GitHub workflow command is deprecated
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
- via CI
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the …
=> chore: use GITHUB_OUTPUT instead of deprecated set-output

.changeset/brave-steaks-drop.md, packages/crypto/README.md, packages/crypto/jest.config.js, packages/crypto/package.json, packages/crypto/setup.js, packages/crypto/src/__tests__/crypto-test.ts, packages/crypto/src/crypto.ts, packages/crypto/src/turnkey.ts, pnpm-lock.yaml
Crypto doesn't work for React Native, and the polyfill didn't include crypto.subtle.verify (for verifyEnclaveSignature), so I had to migrate away from it and use Noble instead.
I reran the tests and added decryptExportBundle tests.
yes …
=> remove use of "crypto" library

.changeset/good-kangaroos-sneeze.md, packages/crypto/README.md
- Added changeset
- Turns our noble's `randomBytes()` uses crypto under the hood, so I updated the readme to reintroduce the React Native crypto polyfill setup
yes - patch
These changes will be used at …
=> Changeset added back for turnkey/crypto

.changeset/smart-chefs-complain.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.client.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/sdk-browser/src/__generated__/sdk-client-base.ts, packages/sdk-browser/src/__generated__/sdk_api_types.ts, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-server/src/__generated__/sdk-client-base.ts, packages/sdk-server/src/__generated__/sdk_api_types.ts, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts
Based on Mono release version v2025.2.1 (most recent) …
=> Update api endpoints for sdk

.changeset/chatty-swans-behave.md, .changeset/early-grapes-teach.md, .changeset/smart-chefs-complain.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
- Update endpoints - surface GetWalletAccount (mono v2025.2.1)
- Upgrade vulnerable elliptic package
- Fix EWK phone number validation
These changes will be used at release time to determine what packages to …
=> Release feb 18

.changeset/spicy-llamas-tease.md, .changeset/stale-ducks-sneeze.md, packages/telegram-cloud-storage-stamper/src/__tests__/stamp-test.ts, packages/telegram-cloud-storage-stamper/src/index.ts
- remove export of `DEFAULT_TURNKEY_CLOUD_STORAGE_KEY`
```
packages/telegram-cloud-storage-stamper build$ rollup -c
[1 lines collapsed]
│ src/index.ts → dist...
│ created dist in 557ms
│
│ src/index.ts → dist...
│ (!) Mixing named and default exports
│ https://rollupjs.org/configuration-options/#output-exports
│ The following entry modules are using named and default export
│ src/index.ts
│ Consumers of your bundle will have to use chunk.default to acc
│ created dist in 607ms
└─ Done in 1.4s
```
```
packages/telegram-cloud-storage-stamper build$ rollup -c
│
│ src/index.ts → dist...
│ created dist in 600ms
│
│ src/index.ts → dist...
│ created dist in 500ms
└─ Done in 1.3s
```
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm …
=> chore: use named exports in Telegram package

.changeset/swift-impalas-kiss.md, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-server/src/actions.ts, packages/sdk-server/src/index.ts
Surface a server action that is leveraged to either get or create a suborg (used for continue with... flows)
These changes will be used at release time to determine what packages to publish and how to bump …
=> getOrCreateSuborg server action

.changeset/modern-cooks-approve.md, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json
Fix OTP sign up flow issue in EWK …
=> Patch release sdk-react mar5

.changeset/old-ghosts-obey.md, examples/react-components/src/app/dashboard/page.tsx, packages/sdk-browser/src/sdk-client.ts
=> Update user auth abstraction

.changeset/shy-fishes-kneel.md, examples/react-components/src/app/layout.tsx, packages/iframe-stamper/src/index.ts, packages/sdk-browser/src/__types__/base.ts, packages/sdk-browser/src/sdk-client.ts, packages/sdk-react/src/contexts/TurnkeyContext.tsx
linked to: https://github.com/tkhq/frames/pull/65 …
=> Custom TTL for iframe

package.json, pnpm-lock.yaml
$title
should be able to remove the outright explores, and instead lean on the override configs
These changes will be used at release time to determine what packages to publish and how to bump their version. …
=> remove cve ignores

examples/react-components/src/app/dashboard/page.tsx, examples/react-components/src/app/page.tsx
- Handle uncaught exception during page reload when session is expired
- `examples/react-components/src/app/page.tsx`
- replaced deprecated `.getReadWriteSession()` with `.getSession()`
- removed session expiry logic as that is handled within `.getSession()`
- `examples/react-components/src/app/dashboard/page.tsx`
- removed session expiry logic as that is handled within `.getSession()`
- authenticated via OTP and set `sessionExpiration` to 30 seconds
- refreshed page while session was still active and page rehydrated
- refreshed page after session expired, `handleLogout()` was called and the app navigated back to the auth screen
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm …
=> chore: update manageSession logic

.changeset/tiny-pianos-rest.md, packages/sdk-browser/src/__clients__/browser-clients.ts
In the current code, calling `loginWithPasskey` or `loginWithWallet` with `SessionType.READ_ONLY` throws an error, even if the login is successful.
call `loginWithPasskey` with `SessionType.READ_ONLY` and correct parameters, error will be thrown from: https://github.com/tkhq/sdk/blob/95be4b9b131a61c76bec1d5e6dc4ecc4b11951e1/packages/sdk-browser/src/__clients__/browser-clients.ts#L306
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?pla …
=> fix: unexpected error when using read-only session type

.changeset/pretty-seahorses-cross.md, packages/sdk-browser/src/__clients__/browser-clients.ts, packages/sdk-browser/src/storage.ts
I noticed that the original session key`@turnkey/session/v1` is deprecated and changed to `@turnkey/session/v2`, and functions like `TurnkeyBrowserClient.loginWithPasskey()`, `TurnkeyBrowserClient.loginWithWallet()`, `TurnkeyBrowserSDK.currentUserSession()` is already changed to use the new key name.
But currently the `TurnkeyBrowserClient.login()` function is still using the deprecated key, this will result in inconsistent read/write when combining the functions above.
In browser, login with `passkeyClient` and then read session with `TurnkeyBrowserSDK`
```
const config = {
apiBaseUrl: "https://api.turnkey.com",
defaultOrganizationId: process.env.TURNKEY_ORGANIZATION_ID,
serverSignUrl: "https://your-server-sign-url.com",
};
const turnkeySDK = new Turnkey(config);
const passkeyClient = …
```
=> fix: update session handling of `TurnkeyBrowserClient.login()` to align with other functions

.changeset/brown-insects-double.md, packages/sdk-react/src/components/auth/Auth.tsx
Custom passkey naming for EWK createUserPasskey …
=> PasskeyConfig Auth component

.changeset/thirty-buckets-camp.md, packages/sdk-browser/src/__generated__/sdk-client-base.ts, packages/sdk-server/src/__generated__/sdk-client-base.ts
Result was defaulting to an activity version we were not ready to release due to a faulty codegen script. This reverts that change.
These changes will be used at release time to determine what packages to …
=> Patch: Fix improper result init otp auth

.changeset/thirty-buckets-camp.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
=> Release: mar26 patch fix initOtp bug for sdk-server/sdk-browser + associated dependency updates

examples/email-auth-local-storage/README.md
We previously were showing the email auth flow in this example README, but it has references to iframes. That was confusing.
I opted to remove this diagram since we point to our docs and the canonical email auth example, both of which have this diagram already.
=> Remove diagram which mentions iframes (email auth local storage example)

.changeset/silver-chicken-boil.md, packages/iframe-stamper/src/index.ts
$title
Frames counterpart: https://github.com/tkhq/frames/pull/64 …
=> add live getter for iframe targetEmbeddedKey

.changeset/rude-colts-poke.md, packages/http/src/index.ts, packages/http/src/version.ts
- Remove PublicApiService export which has been deprecated
- Cleaning this up separately from the docs generation PR
- locally
These changes will be used at release time to determine what packages to publish …
=> feat: remove export for deprecated PublicApiService

.changeset/itchy-gorillas-fetch.md, packages/viem/src/index.ts
cc https://github.com/paco0x for credit: https://github.com/tkhq/sdk/pull/543
In the `@turnkey/viem` package, the `organizationId` parameter is ignored when using a client other than `TurnkeyClient` (e.g., `passkeyClient`). Consequently, the SDK calls the client without the specified `organizationId`, which is unintended.
This change is to align with the Solana SDK code in here: https://github.com/tkhq/sdk/blob/0a97724d265e803067bba74762d4e495855e204c/packages/solana/src/index.ts#L161
example in frontend context:
```typescript
// get the passkeyClient
const { passkeyClient } = useTurnkey();
const viemAccount = await createAccount({
client: passkeyClient,
organizationId: "YOUR_ORGANIZATION_ID",
signWith: "YOUR_EVM_ADDRESS",
});
await viemAccount.signMessage({message: "hello"});
```
In the …
=> fix: adding missed organizationId param 

.changeset/brave-keys-punch.md, examples/email-auth/src/pages/index.tsx, packages/iframe-stamper/src/index.ts, packages/sdk-browser/src/__clients__/browser-clients.ts
$title
Accompying `tkhq/frames` change (with demo vid): https://github.com/tkhq/frames/pull/67 
https://github.com/user-attachments/assets/2672cea8-d58d-43f0-b0b7-ca3044504c33
These changes will be used at …
=> update iframe stamper to have methods to refresh an embedded key

packages/viem/src/__tests__/index-test.ts
$title
Hopefully, this resolves some test flakiness
- locally, against a local anvil instance
These changes will be used at release time to determine what packages to publish and how to bump their version. …
=> wait for transaction confirmation in unit tests

.changeset/nine-tigers-grab.md, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/OtpVerification.tsx
$title
This will ensure that whenever users take auth-related actions, there will be a target embedded key to use
- locally, via `examples/react-components`
yes
These changes will be used at release time to …
=> ensure presence of iframe embedded key

.changeset/fifty-plants-grin.md, .changeset/nine-tigers-grab.md, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json
=> release eip-1193-provider and sdk-react

.changeset/ninety-spies-sing.md, packages/sdk-react-native/README.md, packages/sdk-react-native/src/constants.ts, packages/sdk-react-native/src/contexts/TurnkeyContext.tsx, packages/sdk-react-native/src/storage.ts
client asked for abstraction to be able to refresh sessions before they expire (i.e extend the session)
went a step up and also added a warning function that runs 15 seconds before the session expiries - to make these an even easier process …
=> refreshSession

packages/sdk-react-native/README.md, packages/sdk-react-native/package.json, packages/sdk-react-native/src/constants.ts, packages/sdk-react-native/src/contexts/TurnkeyContext.tsx, pnpm-lock.yaml
=> handleGoogleOAuth for sdk-react-native

.changeset/chilly-turkeys-begin.md, packages/http/src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts, packages/http/src/__generated__/services/coordinator/public/v1/public_api.swagger.json, packages/http/src/__generated__/services/coordinator/public/v1/public_api.types.ts, packages/sdk-browser/src/__inputs__/public_api.swagger.json, packages/sdk-browser/src/__inputs__/public_api.types.ts, packages/sdk-server/src/__inputs__/public_api.swagger.json, packages/sdk-server/src/__inputs__/public_api.types.ts
=> release per mono v2025 4 4

.changeset/chilly-turkeys-begin.md, .changeset/lucky-terms-pump.md, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react-native/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/README.md, packages/viem/package.json
$title
Releases mono v2025.4.4, and corresponding changes
Also bumps @turnkey/viem
These changes will be used at release time to determine what packages to publish and how to bump their version. For more …
=> update packages and changelogs

.changeset/small-dragons-repair.md, packages/api-key-stamper/src/utils.ts, packages/api-key-stamper/src/webcrypto.ts
Clarifying in error messages and docs that our API key import assumes a P-256 API key.
=> Better error message and JS docs for API key import

.changeset/eighty-clouds-check.md, .changeset/eleven-jeans-flash.md, packages/sdk-react-native/README.md, packages/sdk-react-native/src/constants.ts, packages/sdk-react-native/src/contexts/TurnkeyContext.tsx
removed storing the embeddedKey in secure storage for refreshSession
Whats the reason?
- before we were creating it then getting it from secure storage right after, there is no need to store it
- Injective reported a `TurnkeyReactNativeError: Embedded key not found when refreshing the session` error sometimes. I am suspecting that since the two events are so close together on some slower devices this might be the cause.
slack thread can be found [here](https://turnkeycrypto.slack.com/archives/C08NZQ30FA6/p1746007618850369)
yes
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about …
=> sdk-react-native refreshSession bug fix

.changeset/eight-geckos-scream.md, packages/sdk-react/src/components/auth/Apple.tsx, packages/sdk-react/src/components/auth/Auth.tsx, packages/sdk-react/src/components/auth/Facebook.tsx, packages/sdk-react/src/components/auth/Google.tsx, packages/sdk-react/src/components/auth/OtpVerification.tsx, packages/sdk-react/src/components/auth/otp.tsx
You can now pass in `openInPage` into the `authConfig` to replace the current page with the oAuth login. 
Otp input not properly changes the keyboard type on mobile depending on if the otp is alphanumeric or not
Requested by Spyre
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the command) along with the type of [semver change (major.minor.patch)](https://semver.org/) …
=> Added option for oAuth to replace window. Fixed keyboard input on mobile

packages/crypto/package.json, pnpm-lock.yaml
solve:
- https://github.com/advisories/GHSA-xq7p-g2vc-g82p
```
pnpm audit
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ Homograph attack allows Unicode lookalike characters   │
│                     │ to bypass validation.                                  │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ base-x                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ =5.0.0                                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=5.0.1 …
```
=> dep updates

.changeset/three-beers-check.md, packages/sdk-react/src/components/auth/otp.tsx
sdk-react auth component update
before:
after:
tested on chrome, safari, firefox. All good 👍 
yes
These changes will be used at release time to determine what packages to publish and how to bump their …
=> remove browser spin buttons from number input in auth component

.github/workflows/release.yml, packages/sdk-types/package.json
- adding debugging to ensure chaangeset is present to avoid PR creation …
=> feat: add debugging to release workflow

.github/workflows/release.yml
- set github user to be used during release workflow
- remove title to prevent PR creation
These changes will be used at release time to determine what packages to publish and how to bump their version. For …
=> Configure Git User for release

.github/workflows/release.yml
- use `github-api` for `commitMode` to leverage `tkhq-deploy` perms
- separate version, publish, and github release steps
These changes will be used at release time to determine what packages to publish and …
=> chore: use github-api for the commit

.github/workflows/release.yml, packages/api-key-stamper/package.json, packages/cosmjs/package.json, packages/crypto/package.json, packages/eip-1193-provider/package.json, packages/encoding/package.json, packages/ethers/package.json, packages/http/package.json, packages/iframe-stamper/package.json, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/package.json, packages/sdk-react-native/package.json, packages/sdk-react/package.json, packages/sdk-server/package.json, packages/sdk-types/package.json, packages/solana/package.json, packages/telegram-cloud-storage-stamper/package.json, packages/viem/package.json, packages/wallet-stamper/package.json, packages/webauthn-stamper/package.json
- add version comment for `softprops/action-gh-release`
- updated the release workflow to run using a tag format of `v*.*.*` vs `test-v*.*.*`
- removed workflow debugging steps
- added step to publish packages to [GitHub Packages](https://github.com/orgs/tkhq/packages?repo_name=sdk)
- updated `packages/*/package.json` 
- `repository.url` to use NPM convention of `"git+https://github.com/tkhq/sdk.git"` vs `"https://github.com/tkhq/sdk.git"`
- included package `README.md` in published artifacts
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this …
=> Release Workflow Polish

.github/workflows/js-build.yml, .github/workflows/release.yml
- created separate workflow jobs for `test-pre-prod` and `test-prod` to reduce flakiness
- Tested via [GitHub Action](https://github.com/tkhq/sdk/actions/runs/15123000969)
These changes will be used at …
=> chore: create separate jobs for test suites

.changeset/twenty-ants-yawn.md, packages/sdk-server/package.json, pnpm-lock.yaml
$title
Q: https://github.com/tkhq/sdk/blob/main/packages/sdk-server/src/actions.ts
actions.ts will still work right? I assume so but just a sanity check. It has "use server"  at the top
A: Good catch; I believe it should still work because the “parent” application should be able to interpret it correctly, as long as that application has next installed
- Local example: `examples/react-components`
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-ex …
=> remove nextjs dependency from sdk-server

.github/workflows/release.yml
- updated release tag regex to escape the last character  …
=> chore: update release tag regex

.changeset/poor-trainers-burn.md, examples/delegated-access/CHANGELOG.md, examples/delegated-access/package.json, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/sdk-types/CHANGELOG.md, packages/sdk-types/package.json, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
- The CI step to publish to NPM failed to complete successfully. The updated packages were published to NPM but the package.json's in the git repo were not versioned.
- This PR brings the versions back in line
- https://www.npmjs.com/package/@turnkey/sdk-types?activeTab=versions latest version is 0.1.0
- package.json version is 0.0.2
- checked out latest from main locally
- ran `pnpm changeset version && pnpm run version`
- ran `corepack enable pnpm && pnpm install -r`
- ran `pnpm run clean-all && pnpm run build-all`
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the …
=> Manually version packages due to NPM publish

.changeset/proud-keys-whisper.md, .changeset/sweet-onions-design.md, examples/react-components/src/app/dashboard/page.tsx, packages/encoding/src/index.ts, packages/indexed-db-stamper/src/index.ts, packages/sdk-browser/src/__clients__/browser-clients.ts
=> Allow external keypair reset indexedDbStamper (enables refreshSession for RW)

.changeset/fluffy-doors-film.md, .changeset/lucky-spiders-hammer.md, packages/cosmjs/src/index.ts, packages/eip-1193-provider/src/turnkey.ts, packages/ethers/src/index.ts, packages/http/src/base.ts, packages/http/src/index.ts, packages/solana/src/index.ts, packages/viem/src/index.ts
Now checking the constructor name of the class instead of using `instanceof`. 
Before we were checking `client instanceof TurnkeyClient` which would return false if turnkey/viem, cosmjs, eip-1193, ethers, or solana and turnkey/http were on different versions
Console log the constructor name when signing:
When TurnkeyHttp client is passed in:
When api client from sdk-server is passed in:
Basically, the constructor name should be sufficient for checking what client is passed in 
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this …
=> "No runner registered" fix for turnkey/viem, cosmjs, eip-1193, ethers, solana

.github/workflows/version.yml
- explicitly checkout main before processing changesets …
=> chore: checkout main

.github/workflows/publish.yml
=> chore: remove the commit message check as it gets overwritten

.changeset/three-frogs-travel.md, packages/api-key-stamper/src/index.ts, packages/sdk-server/src/__types__/base.ts, packages/sdk-server/src/sdk-client.ts
This introduces a `runtimeOverride` option in both `ApiKeyStamper` and `TurnkeyServerSDK` that allows users to explicitly select the crypto environment: "browser", "node", or "purejs"
**Note**: this was added based on an ad-hoc request  …
=> add optional param to override runtime environment in sdk-server 

packages/sdk-react-native/README.md
=> Updated React Native readme to include inappbrowser fix

packages/sdk-react/CHANGELOG.md
The changelog file contained the literal string `<->`, which was interpreted as an invalid or malformed HTML tag by Mintlify. This caused a parsing error when syncing changelogs in our docs repo
These changes …
=> fix invalid changelog format for mintlify

.changeset/sdk-rn-context-initialized.md, packages/sdk-react-native/README.md, packages/sdk-react-native/src/contexts/TurnkeyContext.tsx
Author: @samuelsramko 
Many applications rely on an initialized context to automatically perform operations based on the active or inactive session. I added a simple callback, which is called once the `useEffect` inside the `TurnkeyContext` has finished. …
=> samuelsramko contrib

examples/with-ethers/package.json, examples/with-ethers/src/eip712/erc2612_permit.ts, examples/with-ethers/src/eip712/erc3009_transfer.ts, examples/with-ethers/src/eip712/hyperliquid.ts, examples/with-viem/package.json, examples/with-viem/src/eip712/erc2612_permit.ts, examples/with-viem/src/eip712/erc3009_transfer.ts, examples/with-viem/src/eip712/hyperliquid.ts
This PR introduces signing examples for a Hyperliquid `ApproveAgent` EIP-712 payload, an ERC-2612 permit, and an ERC-3009 Transfer. Examples are provided for both our `ethers` and `viem` packages, and are executable via `pnpm`.
No: PR does not include SDK changes.
=> EIP-712: Signing Examples

.changeset/old-windows-juggle.md, package.json, packages/sdk-browser/src/__clients__/browser-clients.ts
=> Expose keyFormat in extractKeyEncryptedBundle for our iframeClient

.changeset/twenty-eels-cry.md, examples/delegated-access/CHANGELOG.md, examples/delegated-access/package.json, packages/cosmjs/CHANGELOG.md, packages/cosmjs/package.json, packages/eip-1193-provider/CHANGELOG.md, packages/eip-1193-provider/package.json, packages/eip-1193-provider/src/version.ts, packages/ethers/CHANGELOG.md, packages/ethers/package.json, packages/http/CHANGELOG.md, packages/http/package.json, packages/http/src/version.ts, packages/react-native-passkey-stamper/CHANGELOG.md, packages/react-native-passkey-stamper/package.json, packages/sdk-browser/CHANGELOG.md, packages/sdk-browser/package.json, packages/sdk-browser/src/__generated__/version.ts, packages/sdk-react-native/CHANGELOG.md, packages/sdk-react-native/package.json, packages/sdk-react/CHANGELOG.md, packages/sdk-react/package.json, packages/sdk-server/CHANGELOG.md, packages/sdk-server/package.json, packages/sdk-server/src/__generated__/version.ts, packages/solana/CHANGELOG.md, packages/solana/package.json, packages/viem/CHANGELOG.md, packages/viem/package.json
corresponds to mono release v2025.7.1 …
=> chore: release packages

.github/workflows/version-and-publish.yml, .npmrc, .npmrc.ci, examples/with-viem/.npmrc, packages/http/package.json, packages/viem/.npmrc
- remove `@turnkey/viem` specific `.npmrc`
- configure `.npmrc.ci` for use in GitHub Actions
These changes will be used at release time to determine what packages to publish and how to bump their version. For …
=> configure .npmrc.ci and remove viem specific .npmrc

.changeset/few-teachers-boil.md, packages/sdk-server/src/actions.ts
Duplicate suborgs were sometimes being created from our getOrCreateSuborg helper function
These changes will be used at release time to determine what packages to publish and how to bump their version. For …
=> Fix server action fallback leading to dupe suborgs

.changeset/busy-crabs-camp.md, packages/viem/src/index.ts
$title
this resolves an error where signature verification would fail because the signature verification function (`recoverTypedDataAddress`) would encode typed data differently than our implementation of Viem.
locally using examples
yes …
=> use viem's serialization utils

packages/sdk-react/package.json, pnpm-lock.yaml
=> add react 19 to dependency list for `sdk-react`

.changeset/six-drinks-pay.md, packages/viem/src/index.ts
=> update viem implementation to use PAYLOAD_ENCODING_EIP7702_AUTHORIZATION

examples/kitchen-sink/README.md
I was going through the [kitchen-sink example](https://github.com/tkhq/sdk/tree/main/examples/kitchen-sink) in the SDK and realized it was missing the same Getting Started instructions that other example READMEs have. It tripped me up for a bit because I didn't realize the setup steps I needed to take on the monorepo until I started looking at other examples. I made a change to the README to address this.
=> Added setup steps for kitchen sink example

examples/otp-auth/README.md, examples/otp-auth/package.json, examples/otp-auth/src/pages/api/auth.ts, pnpm-lock.yaml
Versioning Problem: The application fails to run with the latest version of the SDK due to versioning issues. I updated the react and next.js packages to fix the issue.
Org ID Problem: When users don't provide a suborgID in the OTP auth form, the API calls fail because the organizationId parameter is empty. Added fallback logic in /api/auth.ts to use the parent org env when suborgID is not provided or empty.
I also updated the README to remind users to login with an already existing user email that has permissions to create wallets. Otherwise, the wallet creation step will fail. 
Ran and tested the app using a test organzation going through the full login flow.
=> Fixes for otp-auth versioning and org id issues

.changeset/slimy-baths-do.md, packages/react-wallet-kit/src/components/import/Import.tsx, packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/react-wallet-kit/src/providers/client/Types.tsx
=> added optional wallet/pk name override for import modals

examples/with-sdk-js/src/app/page.tsx, packages/react-wallet-kit/src/components/export/Export.tsx, packages/react-wallet-kit/src/components/export/ExportWarning.tsx, packages/react-wallet-kit/src/providers/client/Provider.tsx
- Made handleExport methods & handleAddOauth fully async …
=> fixed export and handleAddOauth for sessionless stamping

examples/with-ethers/src/index.ts
Currently when running the demo the below error is returned, due to the fact that the transaction object is not fully populated: https://github.com/tkhq/sdk/blob/b755f006f90ff19b94d9d26bb89c16855f115a57/examples/with-ethers/src/index.ts#L119
```
TurnkeyActivityError: Failed to sign: Turnkey error 3: failed to pre-parse Ethereum transaction (Details: [])
at TurnkeySigner._signTransactionWithErrorWrapping 
```
The ethers signer has a populateTransaction method for sending to the network by populating any missing tx properties.
https://docs.ethers.org/v6/api/providers/#Signer-populateTransaction
Signing the fully populated tx works.
=> connectedSigner: add populateTransaction step before signing tx

.changeset/major-pans-brush.md
cleaning up changelog from [PR 977](https://github.com/tkhq/sdk/pull/977)
packages with changes:
- `@turnkey/sdk-browser`: minor
- `@turnkey/sdk-server`: minor
- `@turnkey/sdk-types`: minor
- `@turnkey/core`: minor
- `@turnkey/http`: minor
all of these came from the mono sync with `v2025.9.5`
**Note**: other packages that list any of these as dependencies will automatically be patched
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?pl …
=> clean up changelogs for release

.changeset/small-lamps-battle.md, packages/react-wallet-kit/src/providers/client/Provider.tsx, packages/react-wallet-kit/src/types/method-types.ts
Context: https://clubturnkey.slack.com/archives/C068436FFSN/p1759428512837959?thread_ts=1759354896.329689&cid=C068436FFSN
**Note:** This is technically a breaking change, but since the function was previously unusable, it’s being released as a patch - this _should_ guarantee no existing users will be affected
If updating one of our packages, you'll likely need to add a changeset to your PR. To do so, run [`pnpm changeset`](https://pnpm.io/using-changesets#adding-new-changesets). `pnpm changeset` will generate a file where you should write a human friendly message about the changes. Note how this ([example](https://github.com/tkhq/sdk/blob/b409cd06790f011bf939adcf0755499b8e7497ae/.changeset/extra-http-exports.md?plain=1#L1)) includes the package name (should be auto added by the command) …
=> add `publicKey` field to `onOauthSuccess` callback
